# Generated by Django 4.2.7 on 2025-11-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de Plantilla')),
                ('subject', models.CharField(max_length=500, verbose_name='Asunto')),
                ('body_html', models.TextField(verbose_name='Cuerpo HTML')),
                ('body_text', models.TextField(blank=True, verbose_name='Cuerpo Texto Plano')),
                ('available_variables', models.TextField(blank=True, help_text='Variables separadas por comas (ej: {{company_name}}, {{contact_name}}, {{quote_number}})', verbose_name='Variables Disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn')], max_length=20, verbose_name='Plataforma')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de Imagen')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de Video')),
                ('hashtags', models.CharField(blank=True, help_text='Separados por espacios', max_length=500, verbose_name='Hashtags')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('programado', 'Programado'), ('publicado', 'Publicado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('scheduled_time', models.DateTimeField(verbose_name='Hora Programada')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado en')),
                ('external_post_id', models.CharField(blank=True, help_text='ID del post en la plataforma social', max_length=255, verbose_name='ID Externo del Post')),
                ('external_post_url', models.URLField(blank=True, verbose_name='URL del Post Externo')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Post de Redes Sociales',
                'verbose_name_plural': 'Posts de Redes Sociales',
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['platform', 'status'], name='MarketingMo_platfor_0648d9_idx'), models.Index(fields=['scheduled_time'], name='MarketingMo_schedul_99d4bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Campaña')),
                ('segment_filter', models.JSONField(default=dict, help_text='Criterios para filtrar leads (ej: {"status": "calificado", "country": "Ecuador"})', verbose_name='Filtro de Segmento')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('enviando', 'Enviando'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programada para')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada en')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Total de Destinatarios')),
                ('emails_sent', models.IntegerField(default=0, verbose_name='Emails Enviados')),
                ('emails_failed', models.IntegerField(default=0, verbose_name='Emails Fallidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='MarketingModule.emailtemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Campaña de Email',
                'verbose_name_plural': 'Campañas de Email',
                'ordering': ['-created_at'],
            },
        ),
    ]
