# Generated by Django 4.2.7 on 2025-11-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0001_initial'),
        ('MarketingModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de Landing Page')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('distribution_channels', models.JSONField(default=list, help_text='Lista de canales habilitados para esta landing page', verbose_name='Canales de Distribución')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('public_url_slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Pública (Slug)')),
                ('custom_branding', models.JSONField(blank=True, default=dict, help_text='Colores, logos, y otros elementos de marca', verbose_name='Personalización de Marca')),
                ('total_visits', models.IntegerField(default=0, verbose_name='Total de Visitas')),
                ('total_submissions', models.IntegerField(default=0, verbose_name='Total de Envíos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_existing_customer', models.BooleanField(default=False, verbose_name='¿Es Cliente Existente?')),
                ('existing_customer_ruc', models.CharField(blank=True, help_text='RUC del cliente existente para búsqueda en CRM', max_length=13, verbose_name='RUC (Cliente Existente)')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Apellidos')),
                ('is_company', models.BooleanField(default=False, verbose_name='¿Es Empresa?')),
                ('company_name', models.CharField(blank=True, max_length=500, verbose_name='Razón Social')),
                ('company_ruc', models.CharField(blank=True, max_length=13, verbose_name='RUC de Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('transport_type', models.CharField(choices=[('air', 'Aéreo'), ('ocean_lcl', 'Marítimo LCL'), ('ocean_fcl', 'Marítimo FCL')], max_length=20, verbose_name='Tipo de Transporte')),
                ('incoterm', models.CharField(max_length=10, verbose_name='Incoterm')),
                ('is_general_cargo', models.BooleanField(default=True, verbose_name='Carga General')),
                ('is_dg_cargo', models.BooleanField(default=False, verbose_name='Carga Peligrosa (DG)')),
                ('msds_document', models.FileField(blank=True, help_text='Obligatorio para carga peligrosa', null=True, upload_to='landing_submissions/msds/', verbose_name='Documento MSDS')),
                ('additional_documents', models.JSONField(blank=True, default=list, help_text='Lista de URLs/paths de documentos adicionales', verbose_name='Documentos Adicionales')),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Bruto (KG)')),
                ('pieces_quantity', models.IntegerField(verbose_name='Cantidad de Piezas')),
                ('dimension_unit', models.CharField(choices=[('cm', 'Centímetros'), ('inches', 'Pulgadas')], default='cm', max_length=10, verbose_name='Unidad de Medida')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largo')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancho')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alto')),
                ('total_cbm', models.DecimalField(blank=True, decimal_places=4, help_text='Para Ocean LCL', max_digits=10, null=True, verbose_name='CBM Total (Metros Cúbicos)')),
                ('is_stackable', models.BooleanField(default=True, verbose_name='¿Es Apilable?')),
                ('container_type', models.CharField(blank=True, choices=[('20gp', '1x20GP'), ('40gp', '1x40GP'), ('40hc', '1x40HC'), ('40nor', '1x40NOR'), ('40rf', '1x40RF'), ('20rf', '1x20RF'), ('40ot_hc', '1x40 OT HC'), ('20flat', '1x20 Flat Rack'), ('40flat', '1x40 Flat Rack'), ('20ot', '1x20 OT'), ('40ot', '1x40 OT')], help_text='Solo para Ocean FCL', max_length=20, verbose_name='Tipo de Contenedor')),
                ('airport_origin', models.CharField(blank=True, max_length=100, verbose_name='Aeropuerto de Origen')),
                ('airport_destination', models.CharField(blank=True, max_length=100, verbose_name='Aeropuerto de Destino')),
                ('pol_port_of_lading', models.CharField(blank=True, max_length=100, verbose_name='Puerto de Embarque (POL)')),
                ('pod_port_of_discharge', models.CharField(blank=True, max_length=100, verbose_name='Puerto de Descarga (POD)')),
                ('pickup_address', models.TextField(blank=True, help_text='Opcional para cálculo de costo de pickup', verbose_name='Dirección de Recogida en Origen')),
                ('quote_validity_days', models.IntegerField(blank=True, help_text='Calculado automáticamente según tipo de transporte y origen', null=True, verbose_name='Validez de Cotización (Días)')),
                ('origin_region', models.CharField(blank=True, help_text='Asia, Southeast Asia, Europa, América, etc.', max_length=100, verbose_name='Región de Origen')),
                ('submission_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Envío')),
                ('submission_source_channel', models.CharField(blank=True, help_text='Email, WhatsApp, etc.', max_length=20, verbose_name='Canal de Origen')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('cotizado', 'Cotizado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('created_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_submissions', to='SalesModule.lead', verbose_name='Lead Creado')),
                ('created_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_submissions', to='SalesModule.quote', verbose_name='Cotización Creada')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='MarketingModule.landingpage', verbose_name='Landing Page')),
            ],
            options={
                'verbose_name': 'Envío de Landing Page',
                'verbose_name_plural': 'Envíos de Landing Pages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landing_page', 'status'], name='MarketingMo_landing_a6e3b8_idx'), models.Index(fields=['created_at'], name='MarketingMo_created_caf220_idx'), models.Index(fields=['existing_customer_ruc'], name='MarketingMo_existin_4488b2_idx'), models.Index(fields=['company_ruc'], name='MarketingMo_company_3c0ad8_idx')],
            },
        ),
    ]
