# Generated by Django 4.2.7 on 2025-11-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketingModule', '0002_landingpage_landingpagesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesubmission',
            name='cargo_cif_value_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Requerido para cálculo de seguro', max_digits=12, null=True, verbose_name='Valor CIF de Mercancía (USD)'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='inland_transport_city',
            field=models.CharField(blank=True, help_text='Ciudad de destino final en Ecuador', max_length=100, verbose_name='Ciudad de Entrega (Ecuador)'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='inland_transport_full_address',
            field=models.TextField(blank=True, help_text='Dirección completa generada automáticamente', verbose_name='Dirección Completa de Entrega'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='inland_transport_references',
            field=models.TextField(blank=True, help_text='Referencias adicionales para ubicar la dirección', verbose_name='Referencias de Dirección'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='inland_transport_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='inland_transport_street_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Calle'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='inland_transport_zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='lead_comments',
            field=models.TextField(blank=True, help_text='Observaciones o solicitudes especiales del cliente', verbose_name='Comentarios Adicionales del Cliente'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='needs_customs_clearance',
            field=models.BooleanField(default=False, help_text='Servicio de desaduanización: USD 295 + 15% IVA por importación', verbose_name='¿Requiere Desaduanización?'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='needs_inland_transport',
            field=models.BooleanField(default=False, help_text='Transporte desde puerto/aeropuerto POD hasta bodega del cliente', verbose_name='¿Requiere Transporte Terrestre Interno?'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='needs_insurance',
            field=models.BooleanField(default=False, help_text='Seguro: 0.35% del valor CIF o mínimo USD 50 + 15% IVA', verbose_name='¿Requiere Seguro de Mercancía?'),
        ),
    ]
