# Generated by Django 4.2.7 on 2025-11-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketingModule', '0003_landingpagesubmission_cargo_cif_value_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlandTransportRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('GUAYAQUIL', 'Guayaquil (perímetro urbano)'), ('MANTA', 'Manta'), ('MACHALA', 'Machala'), ('CUENCA', 'Cuenca'), ('AMBATO', 'Ambato'), ('QUITO', 'Quito')], max_length=50, verbose_name='Ciudad de Destino')),
                ('container_type', models.CharField(choices=[('20gp', '1x20GP'), ('40gp', '1x40GP'), ('40hc', '1x40HC')], help_text='Solo aplica para contenedores estándar: 20GP, 40GP, 40HC', max_length=10, verbose_name='Tipo de Contenedor')),
                ('rate_usd', models.DecimalField(decimal_places=2, help_text='Tarifa desde POD Guayaquil hasta ciudad de destino (incluye retorno de contenedor vacío)', max_digits=10, verbose_name='Tarifa en USD')),
                ('description', models.TextField(blank=True, help_text='Detalles adicionales del servicio de transporte', verbose_name='Descripción del Servicio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tarifa de Transporte Terrestre',
                'verbose_name_plural': 'Tarifas de Transporte Terrestre',
                'ordering': ['city', 'rate_usd'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='MarketingMo_city_615582_idx'), models.Index(fields=['container_type'], name='MarketingMo_contain_43db65_idx')],
                'unique_together': {('city', 'container_type')},
            },
        ),
    ]
