# Generated by Django 4.2.7 on 2025-12-05 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MarketingModule', '0004_inlandtransportrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inlandtransportrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='inlandtransportrate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inland_transport_rates', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='landingpagesubmission',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_page_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_posts', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AlterUniqueTogether(
            name='inlandtransportrate',
            unique_together={('city', 'container_type', 'owner')},
        ),
    ]
