# Generated by Django 4.2.7 on 2025-11-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SalesModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('email', 'Correo Electrónico'), ('web', 'Formulario Web'), ('otro', 'Otro')], max_length=20, verbose_name='Fuente')),
                ('direction', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], default='entrante', max_length=20, verbose_name='Dirección')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Remitente')),
                ('sender_identifier', models.CharField(blank=True, help_text='Teléfono, Email, ID de Usuario, etc.', max_length=255, verbose_name='Identificador del Remitente')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Asunto')),
                ('message_body', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('leido', 'Leído'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('external_message_id', models.CharField(blank=True, help_text='ID del mensaje en la plataforma externa', max_length=255, verbose_name='ID Externo del Mensaje')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leído en')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='SalesModule.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Mensaje de Inbox',
                'verbose_name_plural': 'Mensajes de Inbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'source'], name='CommsModule_lead_id_5b1efe_idx'), models.Index(fields=['status'], name='CommsModule_status_8e5e82_idx'), models.Index(fields=['created_at'], name='CommsModule_created_6cba9e_idx')],
            },
        ),
    ]
