# Generated by Django 4.2.7 on 2025-11-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommsModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('email', 'Email'), ('webhook', 'Custom Webhook')], max_length=20, verbose_name='Tipo de Canal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('connection_method', models.CharField(choices=[('api_key', 'API Key'), ('webhook', 'Webhook'), ('builtin', 'Built-in')], default='builtin', max_length=20, verbose_name='Método de Conexión')),
                ('api_key', models.CharField(blank=True, help_text='Se almacena encriptado', max_length=500, verbose_name='API Key')),
                ('webhook_url', models.URLField(blank=True, help_text='URL para recibir eventos', verbose_name='URL Webhook')),
                ('webhook_secret', models.CharField(blank=True, help_text='Se almacena encriptado', max_length=500, verbose_name='Secreto Webhook')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Datos adicionales específicos del canal', verbose_name='Configuración Adicional')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Conexión')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Conexión de Canal',
                'verbose_name_plural': 'Conexiones de Canales',
                'ordering': ['-connected_at'],
                'unique_together': {('channel_type',)},
            },
        ),
    ]
