# Generated by Django 4.2.7 on 2025-12-05 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CommsModule', '0002_add_channel_connection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelconnection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='channelconnection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_connections', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AlterUniqueTogether(
            name='channelconnection',
            unique_together={('channel_type', 'owner')},
        ),
    ]
