# Generated by Django 4.2.7 on 2025-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('windows', 'Windows Desktop'), ('web', 'Web')], default='web', max_length=20, verbose_name='Plataforma'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead/Importador'), ('asesor', 'Asesor Comercial'), ('admin', 'Administrador')], default='lead', max_length=20, verbose_name='Rol'),
        ),
    ]
