# Generated by Django 4.2.7 on 2025-12-10 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_platform_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead/Importador'), ('admin', 'Administrador')], default='lead', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='LeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, help_text='13 dígitos numéricos del RUC Ecuador', max_length=13, verbose_name='RUC')),
                ('legal_type', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='juridica', max_length=20, verbose_name='Tipo Legal')),
                ('is_active_importer', models.BooleanField(default=False, verbose_name='¿Es importador actualmente?')),
                ('senae_code', models.CharField(blank=True, help_text='Código de operador en SENAE', max_length=50, verbose_name='Código SENAE')),
                ('business_address', models.TextField(blank=True, verbose_name='Dirección Comercial')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('preferred_trade_lane', models.CharField(blank=True, choices=[('china_ecuador', 'China - Ecuador'), ('usa_ecuador', 'USA - Ecuador'), ('europa_ecuador', 'Europa - Ecuador'), ('asia_ecuador', 'Asia - Ecuador'), ('latam_ecuador', 'Latinoamérica - Ecuador')], max_length=50, verbose_name='Ruta Comercial Preferida')),
                ('preferred_transport', models.CharField(blank=True, choices=[('aereo', 'Aéreo'), ('maritimo_fcl', 'Marítimo FCL'), ('maritimo_lcl', 'Marítimo LCL'), ('terrestre', 'Terrestre'), ('multimodal', 'Multimodal')], max_length=20, verbose_name='Transporte Preferido')),
                ('main_products', models.TextField(blank=True, help_text='Descripción de los productos que importa regularmente', verbose_name='Productos Principales')),
                ('average_monthly_volume', models.CharField(blank=True, help_text='Ej: 5-10 TEUs, 50-100 kg aéreo', max_length=100, verbose_name='Volumen Mensual Promedio')),
                ('customs_broker_name', models.CharField(blank=True, max_length=255, verbose_name='Agente de Aduanas')),
                ('customs_broker_code', models.CharField(blank=True, max_length=50, verbose_name='Código Agente Aduanas')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Notificaciones')),
                ('notification_whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Notificaciones')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='Perfil Completo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Importador',
                'verbose_name_plural': 'Perfiles de Importadores',
            },
        ),
    ]
