# Generated by Django 4.2.7 on 2025-12-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role_leadprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(help_text='13 dígitos numéricos del RUC Ecuador - Único en todo el sistema', max_length=13, unique=True, verbose_name='RUC')),
                ('company_name', models.CharField(help_text='Nombre de la empresa asociada al RUC', max_length=255, verbose_name='Razón Social')),
                ('is_primary', models.BooleanField(default=False, help_text='Si es el RUC principal del usuario', verbose_name='Es RUC Principal')),
                ('status', models.CharField(choices=[('primary', 'RUC Principal'), ('pending', 'Pendiente Aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('justification', models.TextField(blank=True, help_text='Razón para registrar este RUC adicional', verbose_name='Justificación')),
                ('relationship_description', models.CharField(blank=True, help_text='Ej: Empresa filial, Representante legal, etc.', max_length=255, verbose_name='Relación con RUC Principal')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas del Master Admin sobre la aprobación/rechazo', verbose_name='Notas del Administrador')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('is_oce_registered', models.BooleanField(default=False, help_text='Si el RUC está registrado como Operador de Comercio Exterior', verbose_name='Registrado como OCE en SENAE')),
                ('senae_verification_date', models.DateField(blank=True, null=True, verbose_name='Fecha Verificación SENAE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruc_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rucs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'RUC de Cliente',
                'verbose_name_plural': 'RUCs de Clientes',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerruc',
            constraint=models.UniqueConstraint(fields=('ruc',), name='unique_ruc_system_wide'),
        ),
    ]
