# Generated by Django 4.2.7 on 2025-12-21 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_customer_ruc_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts_enabled', models.BooleanField(default=True, help_text='Recibir notificaciones de tracking por email', verbose_name='Alertas por Email')),
                ('push_alerts_enabled', models.BooleanField(default=True, help_text='Recibir notificaciones push en el teléfono', verbose_name='Alertas Push')),
                ('milestone_updates', models.BooleanField(default=True, help_text='Recibir alertas cuando la carga alcance un nuevo hito', verbose_name='Actualizaciones de Hitos')),
                ('eta_changes', models.BooleanField(default=True, help_text='Recibir alertas cuando cambie la fecha estimada de llegada', verbose_name='Cambios de ETA')),
                ('document_updates', models.BooleanField(default=True, help_text='Recibir alertas sobre nuevos documentos disponibles', verbose_name='Actualizaciones de Documentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
    ]
