# Generated by Django 4.2.7 on 2025-12-23 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead/Importador'), ('admin', 'Administrador'), ('freight_forwarder', 'Freight Forwarder')], default='lead', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='FreightForwarderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de Empresa')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de Contacto')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('is_verified', models.BooleanField(default=False, help_text='El Freight Forwarder ha sido verificado por Master Admin', verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil Freight Forwarder',
                'verbose_name_plural': 'Perfiles Freight Forwarder',
            },
        ),
        migrations.CreateModel(
            name='FFInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del Freight Forwarder')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de Empresa')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Token de Invitación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('accepted', 'Aceptada'), ('expired', 'Expirada'), ('revoked', 'Revocada')], default='pending', max_length=20, verbose_name='Estado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptada en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada en')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ff_invitations_accepted', to=settings.AUTH_USER_MODEL, verbose_name='Aceptada Por')),
            ],
            options={
                'verbose_name': 'Invitación FF',
                'verbose_name_plural': 'Invitaciones FF',
                'ordering': ['-created_at'],
            },
        ),
    ]
