# Generated by Django 4.2.7 on 2025-12-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ff_portal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFRouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('all', 'Todos'), ('FCL', 'Marítimo FCL'), ('LCL', 'Marítimo LCL'), ('AEREO', 'Aéreo')], default='all', help_text='Tipo de transporte que maneja este FF', max_length=20, verbose_name='Tipo de Transporte')),
                ('origin_country', models.CharField(blank=True, help_text='Deje vacío para todos los países', max_length=100, verbose_name='País de Origen')),
                ('origin_port', models.CharField(blank=True, help_text='POL o aeropuerto específico. Deje vacío para todos.', max_length=100, verbose_name='Puerto/Aeropuerto de Origen')),
                ('destination_city', models.CharField(blank=True, help_text='Ciudad de destino en Ecuador. Deje vacío para todas.', max_length=100, verbose_name='Ciudad de Destino')),
                ('carrier_name', models.CharField(blank=True, help_text='Nombre de la naviera o aerolínea. Deje vacío para todas.', max_length=100, verbose_name='Naviera/Aerolínea')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Mayor prioridad = menor número. Se asigna el FF con mayor prioridad que coincida.', verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('freight_forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='accounts.freightforwarderprofile', verbose_name='Freight Forwarder')),
            ],
            options={
                'verbose_name': 'Asignación de Ruta FF',
                'verbose_name_plural': 'Asignaciones de Rutas FF',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FFGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_mode', models.CharField(choices=[('single', 'FF Único Global'), ('multi', 'Asignación por Criterios'), ('manual', 'Asignación Manual')], default='manual', help_text='Define cómo se asignan los FF a los embarques', max_length=20, verbose_name='Modo de Asignación')),
                ('auto_assign_on_ro', models.BooleanField(default=True, help_text='Asignar automáticamente FF cuando se genera el Routing Order', verbose_name='Auto-asignar al generar RO')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre la configuración de FF', verbose_name='Notas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('default_ff', models.ForeignKey(blank=True, help_text='FF que maneja todos los embarques en modo "single" o como fallback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_default_ff', to='accounts.freightforwarderprofile', verbose_name='FF por Defecto')),
            ],
            options={
                'verbose_name': 'Configuración Global FF',
                'verbose_name_plural': 'Configuración Global FF',
            },
        ),
    ]
