# Generated by Django 4.2.7 on 2025-12-23 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ff_config_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RUCApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_number', models.CharField(help_text='Stored for reference even if RUC is deleted', max_length=13, verbose_name='Número de RUC')),
                ('company_name', models.CharField(help_text='Stored for reference even if RUC is deleted', max_length=255, verbose_name='Razón Social')),
                ('user_email', models.EmailField(help_text='Stored for reference even if user is deleted', max_length=254, verbose_name='Email del Usuario')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Usuario')),
                ('action', models.CharField(choices=[('approved', 'Aprobado'), ('rejected', 'Rechazado')], max_length=20, verbose_name='Acción')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acción')),
                ('ruc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_history', to='accounts.customerruc', verbose_name='RUC')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruc_approval_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario')),
            ],
            options={
                'verbose_name': 'Historial de Aprobación RUC',
                'verbose_name_plural': 'Historial de Aprobaciones RUC',
                'ordering': ['-performed_at'],
            },
        ),
    ]
