# Generated by Django 5.2.9 on 2025-12-28 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_ruc_approval_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerruc',
            options={'verbose_name': 'RUC de Cliente', 'verbose_name_plural': 'RUCs de Clientes'},
        ),
        migrations.RemoveConstraint(
            model_name='customerruc',
            name='unique_ruc_system_wide',
        ),
        migrations.RemoveField(
            model_name='customerruc',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='customerruc',
            name='is_oce_registered',
        ),
        migrations.RemoveField(
            model_name='customerruc',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='customerruc',
            name='relationship_description',
        ),
        migrations.RemoveField(
            model_name='customerruc',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='customerruc',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='customerruc',
            name='senae_verification_date',
        ),
        migrations.RemoveField(
            model_name='customerruc',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='is_primary',
            field=models.BooleanField(default=True, verbose_name='Es RUC Principal'),
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente Aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rucs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
