# Generated by Django 5.2.9 on 2025-12-28 04:27

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_options_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ffinvitation',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='ffrouteassignment',
            name='freight_forwarder',
        ),
        migrations.RemoveField(
            model_name='freightforwarderprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leadprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rucapprovalhistory',
            name='ruc',
        ),
        migrations.RemoveField(
            model_name='rucapprovalhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Usado para enviar el Regalo Digital anual.', null=True, verbose_name='Fecha de Nacimiento (Cumpleaños)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gift_expiry_date',
            field=models.DateField(blank=True, help_text='El regalo es válido por 1 mes desde el cumpleaños.', null=True, verbose_name='Vencimiento del Regalo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_active_gift',
            field=models.BooleanField(default=False, help_text='El sistema marcará esto automáticamente en su cumpleaños.', verbose_name='¿Tiene Regalo Digital Activo?'),
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Si marca esto, cualquier otro RUC de este usuario dejará de ser principal.', verbose_name='Es RUC Principal'),
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='ruc',
            field=models.CharField(help_text='Ingrese los 13 dígitos. Debe terminar en 001.', max_length=13, unique=True, validators=[accounts.models.validar_ruc_ecuador], verbose_name='Número de RUC'),
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rucs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.DeleteModel(
            name='FFGlobalConfig',
        ),
        migrations.DeleteModel(
            name='FFInvitation',
        ),
        migrations.DeleteModel(
            name='FFRouteAssignment',
        ),
        migrations.DeleteModel(
            name='FreightForwarderProfile',
        ),
        migrations.DeleteModel(
            name='LeadProfile',
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
        migrations.DeleteModel(
            name='RUCApprovalHistory',
        ),
    ]
