# Generated by Django 5.2.9 on 2025-12-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_ffinvitation_accepted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='El sistema calculará automáticamente el vencimiento del regalo.', null=True, verbose_name='Fecha de Nacimiento (Cumpleaños)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gift_expiry_date',
            field=models.DateField(blank=True, help_text='Cálculo automático: 30 días después del cumpleaños.', null=True, verbose_name='Vencimiento del Regalo ($100 OFF)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='has_active_gift',
            field=models.BooleanField(default=False, help_text='Se activa automáticamente en el cumpleaños.', verbose_name='¿Tiene Regalo Digital Activo?'),
        ),
    ]
