# Generated by Django 5.2.9 on 2026-01-01 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerruc',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notas del Admin'),
        ),
        migrations.AddField(
            model_name='customerruc',
            name='is_oce_registered',
            field=models.BooleanField(default=False, verbose_name='Registrado en OCE'),
        ),
        migrations.AddField(
            model_name='customerruc',
            name='justification',
            field=models.TextField(blank=True, verbose_name='Justificación'),
        ),
        migrations.AddField(
            model_name='customerruc',
            name='relationship_description',
            field=models.TextField(blank=True, verbose_name='Descripción de Relación'),
        ),
        migrations.AddField(
            model_name='customerruc',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AddField(
            model_name='customerruc',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rucs', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='customerruc',
            name='senae_verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Verificación SENAE'),
        ),
        migrations.AddField(
            model_name='customerruc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de Empresa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='Ecuador', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha verificado su email.', verbose_name='Email Verificado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='platform',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile App'), ('api', 'API')], default='web', max_length=20, verbose_name='Plataforma de Registro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente Aprobación'), ('primary', 'Principal'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='customerruc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rucs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario'),
        ),
        migrations.CreateModel(
            name='FFInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del Freight Forwarder')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de Empresa')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('expired', 'Expirada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_ff_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación FF',
                'verbose_name_plural': 'Invitaciones FF',
            },
        ),
        migrations.CreateModel(
            name='FreightForwarderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de Empresa')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de Contacto')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil FF',
                'verbose_name_plural': 'Perfiles FF',
            },
        ),
        migrations.CreateModel(
            name='LeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, max_length=13, verbose_name='RUC')),
                ('legal_type', models.CharField(blank=True, choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica'), ('rise', 'RISE')], max_length=20, verbose_name='Tipo de Contribuyente')),
                ('is_active_importer', models.BooleanField(default=False, verbose_name='Importador Activo')),
                ('senae_code', models.CharField(blank=True, max_length=50, verbose_name='Código SENAE')),
                ('business_address', models.TextField(blank=True, verbose_name='Dirección Comercial')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('preferred_trade_lane', models.CharField(blank=True, choices=[('china', 'China'), ('usa', 'Estados Unidos'), ('europe', 'Europa'), ('latam', 'Latinoamérica'), ('other', 'Otro')], max_length=20, verbose_name='Ruta Comercial Preferida')),
                ('preferred_transport', models.CharField(blank=True, choices=[('sea', 'Marítimo'), ('air', 'Aéreo'), ('land', 'Terrestre'), ('multimodal', 'Multimodal')], max_length=20, verbose_name='Transporte Preferido')),
                ('main_products', models.TextField(blank=True, verbose_name='Productos Principales')),
                ('average_monthly_volume', models.CharField(blank=True, max_length=100, verbose_name='Volumen Mensual Promedio')),
                ('customs_broker_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Agente Aduanero')),
                ('customs_broker_code', models.CharField(blank=True, max_length=50, verbose_name='Código Agente Aduanero')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Notificación')),
                ('notification_whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp de Notificación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Lead',
                'verbose_name_plural': 'Perfiles de Leads',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts_enabled', models.BooleanField(default=True, verbose_name='Alertas por Email')),
                ('push_alerts_enabled', models.BooleanField(default=True, verbose_name='Alertas Push')),
                ('milestone_updates', models.BooleanField(default=True, verbose_name='Actualizaciones de Hitos')),
                ('eta_changes', models.BooleanField(default=True, verbose_name='Cambios de ETA')),
                ('document_updates', models.BooleanField(default=True, verbose_name='Actualizaciones de Documentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Reseteo',
                'verbose_name_plural': 'Tokens de Reseteo',
            },
        ),
        migrations.CreateModel(
            name='RUCApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruc_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='accounts.customerruc')),
            ],
            options={
                'verbose_name': 'Historial de Aprobación',
                'verbose_name_plural': 'Historial de Aprobaciones',
            },
        ),
    ]
