# Generated by Django 4.2.7 on 2025-11-22 20:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nombre de Empresa')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Nombre de Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('country', models.CharField(default='Ecuador', max_length=100, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('calificado', 'Calificado'), ('perdido', 'Perdido'), ('convertido', 'Convertido a Oportunidad')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('source', models.CharField(blank=True, help_text='Facebook, Instagram, WhatsApp, Email, etc.', max_length=100, verbose_name='Fuente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=255, verbose_name='Nombre de Oportunidad')),
                ('stage', models.CharField(choices=[('calificacion', 'Calificación'), ('propuesta', 'Propuesta'), ('negociacion', 'Negociación'), ('cerrado_ganado', 'Cerrado Ganado'), ('cerrado_perdido', 'Cerrado Perdido')], default='calificacion', max_length=20, verbose_name='Etapa')),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Estimado (USD)')),
                ('probability', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Probabilidad (%)')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Fecha Esperada de Cierre')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='SalesModule.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Cotización')),
                ('origin', models.CharField(max_length=255, verbose_name='Origen')),
                ('destination', models.CharField(max_length=255, verbose_name='Destino')),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW - Ex Works'), ('FCA', 'FCA - Free Carrier'), ('FAS', 'FAS - Free Alongside Ship'), ('FOB', 'FOB - Free On Board'), ('CFR', 'CFR - Cost and Freight'), ('CIF', 'CIF - Cost, Insurance and Freight'), ('CPT', 'CPT - Carriage Paid To'), ('CIP', 'CIP - Carriage and Insurance Paid To'), ('DAP', 'DAP - Delivered At Place'), ('DPU', 'DPU - Delivered at Place Unloaded'), ('DDP', 'DDP - Delivered Duty Paid')], max_length=3, verbose_name='Incoterm')),
                ('cargo_type', models.CharField(choices=[('FCL', 'FCL - Contenedor Completo'), ('LCL', 'LCL - Carga Suelta'), ('Aereo', 'Aéreo'), ('Terrestre', 'Terrestre')], max_length=20, verbose_name='Tipo de Carga')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Descripción de Carga')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa Base (USD)')),
                ('profit_margin', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Margen de Ganancia Mínimo (USD)')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Final al Cliente (USD)')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('visto', 'Visto'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('expirado', 'Expirado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Visto en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='SalesModule.opportunity', verbose_name='Oportunidad')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('seguimiento_cotizacion', 'Seguimiento de Cotización'), ('llamada', 'Llamada'), ('email', 'Enviar Email'), ('reunion', 'Reunión'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo de Tarea')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('due_date', models.DateTimeField(verbose_name='Fecha Límite')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='SalesModule.lead', verbose_name='Lead')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='SalesModule.quote', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Recordatorio de Tarea',
                'verbose_name_plural': 'Recordatorios de Tareas',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('meeting_type', models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial'), ('telefonica', 'Telefónica')], default='virtual', max_length=20, verbose_name='Tipo de Reunión')),
                ('meeting_datetime', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='Duración (minutos)')),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom, Google Meet, etc.', verbose_name='Link de Reunión')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('google_calendar_synced', models.BooleanField(default=False, verbose_name='Sincronizado con Google Calendar')),
                ('outlook_synced', models.BooleanField(default=False, verbose_name='Sincronizado con Outlook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='SalesModule.lead', verbose_name='Lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='SalesModule.opportunity', verbose_name='Oportunidad')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['meeting_datetime'],
            },
        ),
    ]
