# Generated by Django 4.2.7 on 2025-11-30 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la API')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Clave API')),
                ('secret', models.CharField(blank=True, max_length=255, verbose_name='Secreto')),
                ('webhook_url', models.URLField(blank=True, help_text='URL para recibir eventos', verbose_name='URL del Webhook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('service_type', models.CharField(choices=[('zapier', 'Zapier'), ('custom', 'Custom Webhook'), ('stripe', 'Stripe'), ('sendgrid', 'SendGrid'), ('whatsapp', 'WhatsApp'), ('other', 'Otro')], default='custom', max_length=50, verbose_name='Tipo de Servicio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkLeadImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bulk_imports/', verbose_name='Archivo')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('xls', 'Excel 97-2003'), ('txt', 'Texto')], max_length=20, verbose_name='Tipo de Archivo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Total de Filas')),
                ('imported_rows', models.IntegerField(default=0, verbose_name='Filas Importadas')),
                ('error_rows', models.IntegerField(default=0, verbose_name='Filas con Error')),
                ('error_details', models.TextField(blank=True, verbose_name='Detalles de Errores')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Importación Masiva de Leads',
                'verbose_name_plural': 'Importaciones Masivas de Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
