# Generated by Django 4.2.7 on 2025-11-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0002_apikey_bulkleadimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_active_importer',
            field=models.BooleanField(default=False, verbose_name='¿Es importador actualmente?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ruc',
            field=models.CharField(blank=True, help_text='13 dígitos numéricos del RUC Ecuador', max_length=13, verbose_name='RUC'),
        ),
    ]
