# Generated by Django 4.2.7 on 2025-11-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0003_lead_is_active_importer_lead_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='legal_type',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='juridica', max_length=20, verbose_name='Tipo Legal'),
        ),
    ]
