# Generated by Django 4.2.7 on 2025-11-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0004_lead_legal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Apellidos'),
        ),
    ]
