# Generated by Django 4.2.7 on 2025-11-30 04:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0006_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('prospecto', 'Prospecto'), ('contacto_establecido', 'Contacto Establecido'), ('proceso_cotizacion', 'Proceso Cotización'), ('oferta_presentada', 'Oferta Presentada'), ('negociacion', 'Negociación'), ('cotizacion_aprobada', 'Cotización Aprobada')], default='nuevo', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='QuoteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255, verbose_name='Puerto/Ciudad Origen')),
                ('destination', models.CharField(max_length=255, verbose_name='Puerto/Ciudad Destino')),
                ('transport_type', models.CharField(choices=[('FCL', 'Marítimo FCL'), ('LCL', 'Marítimo LCL'), ('AEREO', 'Aéreo')], max_length=20, verbose_name='Tipo de Transporte')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Descripción de Carga')),
                ('cargo_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso (KG)')),
                ('cargo_volume_cbm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volumen (CBM)')),
                ('incoterm', models.CharField(blank=True, help_text='FOB, CIF, etc.', max_length=10, verbose_name='Incoterm')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('company_name', models.CharField(max_length=255, verbose_name='Empresa')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Nombre de Contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('contact_whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('cost_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tarifa de Costo (USD)')),
                ('profit_markup', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12, verbose_name='Margen de Ganancia (USD)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Final (USD)')),
                ('cost_rate_source', models.CharField(blank=True, help_text='api, webhook, google_sheets, manual', max_length=50, verbose_name='Fuente de Tarifa')),
                ('status', models.CharField(choices=[('recibida', 'Recibida'), ('validacion_pendiente', 'Validación Pendiente'), ('procesando_costos', 'Procesando Costos'), ('cotizacion_generada', 'Cotización Generada'), ('error_validacion', 'Error en Validación'), ('error_costos', 'Error en Costos')], default='recibida', max_length=30, verbose_name='Estado')),
                ('validation_errors', models.TextField(blank=True, verbose_name='Errores de Validación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesado en')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_submissions', to='SalesModule.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(db_index=True, max_length=255, verbose_name='Origen')),
                ('destination', models.CharField(db_index=True, max_length=255, verbose_name='Destino')),
                ('transport_type', models.CharField(choices=[('FCL', 'Marítimo FCL'), ('LCL', 'Marítimo LCL'), ('AEREO', 'Aéreo')], db_index=True, max_length=20, verbose_name='Tipo de Transporte')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa (USD)')),
                ('source', models.CharField(choices=[('api', 'API'), ('webhook', 'Webhook'), ('google_sheets', 'Google Sheets'), ('manual', 'Manual')], max_length=20, verbose_name='Fuente')),
                ('provider_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Proveedor')),
                ('valid_from', models.DateField(auto_now_add=True, verbose_name='Válido Desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tarifa de Costo',
                'verbose_name_plural': 'Tarifas de Costo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['origin', 'destination', 'transport_type', 'is_active'], name='SalesModule_origin_52967e_idx')],
            },
        ),
    ]
