# Generated by Django 4.2.7 on 2025-12-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0007_alter_lead_status_quotesubmission_costrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(blank=True, help_text='LEAD-001, LEAD-002, etc.', max_length=20, null=True, unique=True, verbose_name='Número de Lead'),
        ),
    ]
