# Generated by Django 4.2.7 on 2025-12-06 18:04

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesModule', '0009_apikey_owner_bulkleadimport_owner_costrate_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=20, unique=True, verbose_name='Número de Cotización')),
                ('tipo_carga', models.CharField(choices=[('aerea', 'Aérea'), ('maritima', 'Marítima'), ('terrestre', 'Terrestre')], max_length=20, verbose_name='Tipo de Carga')),
                ('origen_pais', models.CharField(max_length=100, verbose_name='País de Origen')),
                ('origen_ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad de Origen')),
                ('destino_ciudad', models.CharField(max_length=100, verbose_name='Ciudad de Destino')),
                ('descripcion_mercancia', models.TextField(verbose_name='Descripción de Mercancía')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Peso (kg)')),
                ('volumen_cbm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volumen (m³)')),
                ('valor_mercancia_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor de Mercancía (USD)')),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW - Ex Works'), ('FOB', 'FOB - Free On Board'), ('CIF', 'CIF - Cost, Insurance & Freight'), ('CFR', 'CFR - Cost & Freight'), ('DDP', 'DDP - Delivered Duty Paid')], default='FOB', max_length=10, verbose_name='Incoterm')),
                ('requiere_seguro', models.BooleanField(default=False, verbose_name='Requiere Seguro')),
                ('requiere_transporte_interno', models.BooleanField(default=False, verbose_name='Requiere Transporte Interno')),
                ('notas_adicionales', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('flete_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Flete (USD)')),
                ('seguro_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Seguro (USD)')),
                ('aduana_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Agenciamiento Aduanero (USD)')),
                ('transporte_interno_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Transporte Interno (USD)')),
                ('otros_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Otros Gastos (USD)')),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total (USD)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cotizado', 'Cotizado'), ('aprobada', 'Aprobada'), ('ro_generado', 'RO Generado'), ('en_transito', 'En Tránsito'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('ro_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de RO')),
                ('shipper_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Shipper')),
                ('shipper_address', models.TextField(blank=True, verbose_name='Dirección del Shipper')),
                ('consignee_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Consignatario')),
                ('consignee_address', models.TextField(blank=True, verbose_name='Dirección del Consignatario')),
                ('notify_party', models.CharField(blank=True, max_length=255, verbose_name='Notify Party')),
                ('fecha_embarque_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Embarque Estimada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('lead_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_cotizaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Lead')),
            ],
            options={
                'verbose_name': 'Cotización de Lead',
                'verbose_name_plural': 'Cotizaciones de Leads',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
