# Generated by Django 4.2.7 on 2025-12-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0010_leadcotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='consignee_address',
            field=models.TextField(blank=True, verbose_name='Dirección del Consignatario'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='consignee_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del Consignatario'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='fecha_embarque_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Embarque'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='notify_party',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notify Party'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='ro_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número de RO'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='shipper_address',
            field=models.TextField(blank=True, verbose_name='Dirección del Shipper'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del Shipper'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='submission_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número de Solicitud'),
        ),
        migrations.AlterField(
            model_name='quotesubmission',
            name='status',
            field=models.CharField(choices=[('recibida', 'Recibida'), ('validacion_pendiente', 'Validación Pendiente'), ('procesando_costos', 'Procesando Costos'), ('cotizacion_generada', 'Cotización Generada'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('ro_generado', 'RO Generado'), ('en_transito', 'En Tránsito'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('error_validacion', 'Error en Validación'), ('error_costos', 'Error en Costos')], default='recibida', max_length=30, verbose_name='Estado'),
        ),
    ]
