# Generated by Django 4.2.7 on 2025-12-10 02:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesModule', '0011_quotesubmission_consignee_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('coverage_type', models.CharField(choices=[('basico', 'Cobertura Básica'), ('ampliada', 'Cobertura Ampliada'), ('todo_riesgo', 'Todo Riesgo')], max_length=30, verbose_name='Tipo de Cobertura')),
                ('rate_percentage', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Tasa (%)')),
                ('min_premium_usd', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=12, verbose_name='Prima Mínima (USD)')),
                ('deductible_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Deducible (%)')),
                ('insurance_company', models.CharField(blank=True, max_length=255, verbose_name='Aseguradora')),
                ('policy_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Póliza')),
                ('valid_from', models.DateField(verbose_name='Válido Desde')),
                ('valid_until', models.DateField(verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_rates', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Tarifa de Seguro',
                'verbose_name_plural': 'Tarifas de Seguro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomsDutyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(db_index=True, help_text='Código arancelario a 6, 8 o 10 dígitos', max_length=12, verbose_name='Código HS')),
                ('description', models.TextField(verbose_name='Descripción del Producto')),
                ('ad_valorem_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Ad Valorem (%)')),
                ('iva_percentage', models.DecimalField(decimal_places=2, default=Decimal('12'), max_digits=5, verbose_name='IVA (%)')),
                ('fodinfa_percentage', models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=5, verbose_name='FODINFA (%)')),
                ('ice_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='ICE (%)')),
                ('salvaguardia_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Salvaguardia (%)')),
                ('specific_duty_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Arancel Específico (USD/unidad)')),
                ('specific_duty_unit', models.CharField(blank=True, help_text='kg, litro, unidad, etc.', max_length=50, verbose_name='Unidad Específica')),
                ('requires_import_license', models.BooleanField(default=False, verbose_name='Requiere Licencia')),
                ('requires_phytosanitary', models.BooleanField(default=False, verbose_name='Requiere Fitosanitario')),
                ('requires_inen_certification', models.BooleanField(default=False, verbose_name='Requiere INEN')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('valid_from', models.DateField(verbose_name='Válido Desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tarifa Arancelaria',
                'verbose_name_plural': 'Tarifas Arancelarias',
                'ordering': ['hs_code'],
                'indexes': [models.Index(fields=['hs_code', 'is_active'], name='SalesModule_hs_code_ab6e68_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomsBrokerageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('service_type', models.CharField(choices=[('importacion_general', 'Importación General'), ('importacion_courier', 'Importación Courier'), ('importacion_menaje', 'Importación Menaje'), ('exportacion', 'Exportación'), ('transito', 'Tránsito'), ('reexportacion', 'Reexportación')], max_length=30, verbose_name='Tipo de Servicio')),
                ('fixed_rate_usd', models.DecimalField(decimal_places=2, default=Decimal('150'), max_digits=12, verbose_name='Tarifa Fija (USD)')),
                ('percentage_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Porcentaje sobre valor CIF', max_digits=5, verbose_name='Tarifa Variable (%)')),
                ('min_rate_usd', models.DecimalField(decimal_places=2, default=Decimal('150'), max_digits=12, verbose_name='Tarifa Mínima (USD)')),
                ('includes_aforo', models.BooleanField(default=True, verbose_name='Incluye Aforo')),
                ('includes_transmision', models.BooleanField(default=True, verbose_name='Incluye Transmisión')),
                ('includes_almacenaje', models.BooleanField(default=False, verbose_name='Incluye Gestión Almacenaje')),
                ('valid_from', models.DateField(verbose_name='Válido Desde')),
                ('valid_until', models.DateField(verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customs_brokerage_rates', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Tarifa de Agenciamiento Aduanero',
                'verbose_name_plural': 'Tarifas de Agenciamiento Aduanero',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InlandTransportQuoteRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(db_index=True, max_length=100, verbose_name='Ciudad Origen')),
                ('destination_city', models.CharField(db_index=True, max_length=100, verbose_name='Ciudad Destino')),
                ('vehicle_type', models.CharField(choices=[('camion_pequeno', 'Camión Pequeño (hasta 3 ton)'), ('camion_mediano', 'Camión Mediano (3-8 ton)'), ('camion_grande', 'Camión Grande (8-20 ton)'), ('trailer', 'Tráiler (20-30 ton)'), ('contenedor_20', 'Contenedor 20 pies'), ('contenedor_40', 'Contenedor 40 pies')], max_length=30, verbose_name='Tipo de Vehículo')),
                ('rate_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa (USD)')),
                ('rate_per_kg_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Tarifa por kg (USD)')),
                ('estimated_hours', models.IntegerField(blank=True, null=True, verbose_name='Horas Estimadas')),
                ('distance_km', models.IntegerField(blank=True, null=True, verbose_name='Distancia (km)')),
                ('includes_loading', models.BooleanField(default=False, verbose_name='Incluye Carga')),
                ('includes_unloading', models.BooleanField(default=False, verbose_name='Incluye Descarga')),
                ('carrier_name', models.CharField(blank=True, max_length=255, verbose_name='Transportista')),
                ('valid_from', models.DateField(verbose_name='Válido Desde')),
                ('valid_until', models.DateField(verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inland_transport_quote_rates', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Tarifa de Transporte Terrestre (Cotización)',
                'verbose_name_plural': 'Tarifas de Transporte Terrestre (Cotización)',
                'ordering': ['origin_city', 'destination_city'],
                'indexes': [models.Index(fields=['origin_city', 'destination_city', 'vehicle_type', 'is_active'], name='SalesModule_origin__e6c349_idx')],
            },
        ),
        migrations.CreateModel(
            name='FreightRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(db_index=True, max_length=100, verbose_name='País Origen')),
                ('origin_port', models.CharField(db_index=True, max_length=100, verbose_name='Puerto/Aeropuerto Origen')),
                ('destination_country', models.CharField(default='Ecuador', max_length=100, verbose_name='País Destino')),
                ('destination_port', models.CharField(db_index=True, max_length=100, verbose_name='Puerto/Aeropuerto Destino')),
                ('transport_type', models.CharField(choices=[('aereo', 'Aéreo'), ('maritimo_fcl_20', 'Marítimo FCL 20'), ('maritimo_fcl_40', 'Marítimo FCL 40'), ('maritimo_fcl_40hc', 'Marítimo FCL 40HC'), ('maritimo_lcl', 'Marítimo LCL')], db_index=True, max_length=30, verbose_name='Tipo de Transporte')),
                ('rate_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa (USD)')),
                ('unit', models.CharField(choices=[('kg', 'Por Kilogramo'), ('cbm', 'Por Metro Cúbico'), ('container', 'Por Contenedor'), ('shipment', 'Por Embarque')], max_length=20, verbose_name='Unidad')),
                ('min_rate_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tarifa Mínima (USD)')),
                ('carrier_name', models.CharField(blank=True, max_length=255, verbose_name='Naviera/Aerolínea')),
                ('transit_days_min', models.IntegerField(blank=True, null=True, verbose_name='Días Tránsito Mín')),
                ('transit_days_max', models.IntegerField(blank=True, null=True, verbose_name='Días Tránsito Máx')),
                ('valid_from', models.DateField(verbose_name='Válido Desde')),
                ('valid_until', models.DateField(verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_rates', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Tarifa de Flete',
                'verbose_name_plural': 'Tarifas de Flete',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['origin_port', 'destination_port', 'transport_type', 'is_active'], name='SalesModule_origin__9835ad_idx')],
            },
        ),
    ]
