# Generated by Django 4.2.7 on 2025-12-10 03:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0012_insurancerate_customsdutyrate_customsbrokeragerate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Escenario')),
                ('tipo', models.CharField(choices=[('economico', 'Económico'), ('estandar', 'Estándar'), ('express', 'Express')], default='estandar', max_length=20, verbose_name='Tipo')),
                ('flete_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Flete (USD)')),
                ('seguro_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Seguro (USD)')),
                ('agenciamiento_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Agenciamiento (USD)')),
                ('transporte_interno_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Transporte Interno (USD)')),
                ('otros_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Otros (USD)')),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total (USD)')),
                ('tiempo_transito_dias', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Tránsito (días)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Seleccionado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('brokerage_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_scenarios', to='SalesModule.customsbrokeragerate', verbose_name='Tarifa de Agenciamiento')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='SalesModule.leadcotizacion', verbose_name='Cotización')),
                ('freight_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_scenarios', to='SalesModule.freightrate', verbose_name='Tarifa de Flete')),
                ('inland_transport_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_scenarios', to='SalesModule.inlandtransportquoterate', verbose_name='Tarifa de Transporte Interno')),
                ('insurance_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_scenarios', to='SalesModule.insurancerate', verbose_name='Tarifa de Seguro')),
            ],
            options={
                'verbose_name': 'Escenario de Cotización',
                'verbose_name_plural': 'Escenarios de Cotización',
                'ordering': ['tipo', 'total_usd'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('flete', 'Flete Internacional'), ('seguro', 'Seguro de Carga'), ('arancel', 'Aranceles'), ('iva', 'IVA'), ('fodinfa', 'FODINFA'), ('ice', 'ICE'), ('salvaguardia', 'Salvaguardia'), ('agenciamiento', 'Agenciamiento Aduanero'), ('transporte_interno', 'Transporte Interno'), ('almacenaje', 'Almacenaje'), ('handling', 'Handling/Manipuleo'), ('documentacion', 'Documentación'), ('otros', 'Otros')], max_length=30, verbose_name='Categoría')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario_usd', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio Unitario (USD)')),
                ('subtotal_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal (USD)')),
                ('es_estimado', models.BooleanField(default=False, verbose_name='Es Estimado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='SalesModule.quotescenario', verbose_name='Escenario')),
            ],
            options={
                'verbose_name': 'Línea de Cotización',
                'verbose_name_plural': 'Líneas de Cotización',
                'ordering': ['categoria', 'created_at'],
            },
        ),
    ]
