# Generated by Django 4.2.7 on 2025-12-10 03:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesModule', '0013_add_quote_scenario_and_line_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Tracking')),
                ('transport_type', models.CharField(choices=[('aereo', 'Aéreo'), ('maritimo', 'Marítimo'), ('terrestre', 'Terrestre')], max_length=20, verbose_name='Tipo de Transporte')),
                ('carrier_name', models.CharField(max_length=255, verbose_name='Transportista/Naviera')),
                ('bl_awb_number', models.CharField(blank=True, max_length=50, verbose_name='BL/AWB')),
                ('container_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Contenedor')),
                ('origin_country', models.CharField(max_length=100, verbose_name='País Origen')),
                ('origin_city', models.CharField(max_length=100, verbose_name='Ciudad Origen')),
                ('destination_country', models.CharField(default='Ecuador', max_length=100, verbose_name='País Destino')),
                ('destination_city', models.CharField(max_length=100, verbose_name='Ciudad Destino')),
                ('description', models.TextField(verbose_name='Descripción de Mercancía')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso (kg)')),
                ('packages', models.IntegerField(default=1, verbose_name='Número de Bultos')),
                ('estimated_departure', models.DateField(blank=True, null=True, verbose_name='Fecha Salida Estimada')),
                ('actual_departure', models.DateField(blank=True, null=True, verbose_name='Fecha Salida Real')),
                ('estimated_arrival', models.DateField(blank=True, null=True, verbose_name='Fecha Llegada Estimada')),
                ('actual_arrival', models.DateField(blank=True, null=True, verbose_name='Fecha Llegada Real')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega Estimada')),
                ('actual_delivery', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega Real')),
                ('current_status', models.CharField(choices=[('booking_confirmado', 'Booking Confirmado'), ('recogido_origen', 'Recogido en Origen'), ('en_transito_internacional', 'En Tránsito Internacional'), ('arribo_puerto', 'Arribo a Puerto/Aeropuerto'), ('en_aduana', 'En Proceso Aduanero'), ('liberado', 'Liberado de Aduana'), ('en_transito_interno', 'En Tránsito Interno'), ('entregado', 'Entregado'), ('incidencia', 'Con Incidencia')], default='booking_confirmado', max_length=30, verbose_name='Estado Actual')),
                ('current_location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación Actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='SalesModule.leadcotizacion', verbose_name='Cotización')),
                ('lead_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Lead')),
            ],
            options={
                'verbose_name': 'Embarque',
                'verbose_name_plural': 'Embarques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booking_confirmado', 'Booking Confirmado'), ('recogido_origen', 'Recogido en Origen'), ('en_transito_internacional', 'En Tránsito Internacional'), ('arribo_puerto', 'Arribo a Puerto/Aeropuerto'), ('en_aduana', 'En Proceso Aduanero'), ('liberado', 'Liberado de Aduana'), ('en_transito_interno', 'En Tránsito Interno'), ('entregado', 'Entregado'), ('incidencia', 'Con Incidencia')], max_length=30, verbose_name='Estado')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('description', models.TextField(verbose_name='Descripción del Evento')),
                ('event_datetime', models.DateTimeField(verbose_name='Fecha y Hora del Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='SalesModule.shipment', verbose_name='Embarque')),
            ],
            options={
                'verbose_name': 'Evento de Tracking',
                'verbose_name_plural': 'Eventos de Tracking',
                'ordering': ['-event_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PreLiquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField(verbose_name='Descripción del Producto')),
                ('suggested_hs_code', models.CharField(blank=True, max_length=12, verbose_name='Código HS Sugerido')),
                ('confirmed_hs_code', models.CharField(blank=True, max_length=12, verbose_name='Código HS Confirmado')),
                ('hs_code_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Confianza IA (%)')),
                ('ai_reasoning', models.TextField(blank=True, verbose_name='Razonamiento IA')),
                ('fob_value_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor FOB (USD)')),
                ('freight_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Flete (USD)')),
                ('insurance_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Seguro (USD)')),
                ('cif_value_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor CIF (USD)')),
                ('ad_valorem_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Ad Valorem (USD)')),
                ('fodinfa_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='FODINFA (USD)')),
                ('ice_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='ICE (USD)')),
                ('salvaguardia_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Salvaguardia (USD)')),
                ('iva_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='IVA (USD)')),
                ('total_tributos_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total Tributos (USD)')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_pre_liquidations', to=settings.AUTH_USER_MODEL, verbose_name='Confirmada Por')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_liquidations', to='SalesModule.leadcotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Pre-Liquidación',
                'verbose_name_plural': 'Pre-Liquidaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='SalesModule_trackin_b31e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['lead_user', 'current_status'], name='SalesModule_lead_us_54fe89_idx'),
        ),
    ]
