# Generated by Django 4.2.7 on 2025-12-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0014_sprint3_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliquidation',
            name='ai_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado IA'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='permit_descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion Permiso'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='permit_institucion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Institucion Permiso'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='permit_tiempo_estimado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiempo Estimado Tramite'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='permit_tipo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tipo de Permiso'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='permit_tramite_previo',
            field=models.BooleanField(default=False, verbose_name='Tramite Previo al Embarque'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='requires_permit',
            field=models.BooleanField(default=False, verbose_name='Requiere Permiso Previo'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='special_taxes',
            field=models.JSONField(blank=True, default=list, verbose_name='Impuestos Especiales'),
        ),
    ]
