# Generated by Django 4.2.7 on 2025-12-12 03:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0015_add_permit_info_to_preliquidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsdutyrate',
            name='iva_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
