# Generated by Django 4.2.7 on 2025-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0016_update_iva_default_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='ai_ad_valorem_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ad-Valorem % (IA)'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoría (IA)'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='ai_hs_code',
            field=models.CharField(blank=True, help_text='Partida arancelaria sugerida por IA', max_length=20, verbose_name='Código HS (IA)'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='ai_hs_confidence',
            field=models.IntegerField(blank=True, null=True, verbose_name='Confianza HS (%)'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='ai_permit_institutions',
            field=models.TextField(blank=True, help_text='JSON con permisos requeridos', verbose_name='Instituciones de Permiso (IA)'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='ai_requires_permit',
            field=models.BooleanField(default=False, verbose_name='Requiere Permiso (IA)'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='ai_response',
            field=models.TextField(blank=True, help_text='JSON completo de la respuesta de Gemini', verbose_name='Respuesta Completa IA'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='ai_status',
            field=models.CharField(blank=True, help_text='success, fallback, error', max_length=30, verbose_name='Estado IA'),
        ),
    ]
