# Generated by Django 4.2.7 on 2025-12-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0017_add_ai_fields_to_quote_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightrate',
            name='transport_type',
            field=models.CharField(choices=[('aereo', 'Aéreo'), ('maritimo_lcl', 'Marítimo LCL'), ('fcl_20gp', 'FCL 1x20GP'), ('fcl_40gp', 'FCL 1x40GP'), ('fcl_40hc', 'FCL 1x40HC'), ('fcl_40nor', 'FCL 1x40NOR'), ('fcl_20_reefer', 'FCL 1x20 REEFER'), ('fcl_40_reefer', 'FCL 1x40 REEFER'), ('fcl_40_ot_hc', 'FCL 1x40 OT HC'), ('fcl_20_flat_rack', 'FCL 1x20 FLAT RACK'), ('fcl_40_flat_rack', 'FCL 1x40 FLAT RACK'), ('fcl_40_open_top', 'FCL 1x40 OPEN TOP'), ('fcl_20_open_top', 'FCL 1x20 OPEN TOP')], db_index=True, max_length=30, verbose_name='Tipo de Transporte'),
        ),
    ]
