# Generated by Django 4.2.7 on 2025-12-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0018_update_freight_rate_container_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='container_type',
            field=models.CharField(blank=True, choices=[('1x20GP', '1x20GP'), ('1x40GP', '1x40GP'), ('1x40HC', '1x40HC'), ('1x40NOR', '1x40NOR'), ('1x20 REEFER', '1x20 REEFER'), ('1x40 REEFER', '1x40 REEFER'), ('1x40 OT HC', '1x40 OT HC'), ('1x20 FLAT RACK', '1x20 FLAT RACK'), ('1x40 FLAT RACK', '1x40 FLAT RACK'), ('1x40 OPEN TOP', '1x40 OPEN TOP'), ('1x20 OPEN TOP', '1x20 OPEN TOP')], help_text='Solo para FCL', max_length=30, verbose_name='Tipo de Contenedor'),
        ),
    ]
