# Generated by Django 4.2.7 on 2025-12-12 18:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0019_add_container_type_to_quote_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proveedor')),
                ('code', models.CharField(help_text='Código corto único: MSC, DHL, etc.', max_length=20, unique=True, verbose_name='Código')),
                ('transport_type', models.CharField(choices=[('FCL', 'Marítimo FCL'), ('LCL', 'Marítimo LCL'), ('AEREO', 'Aéreo')], db_index=True, max_length=10, verbose_name='Tipo de Transporte')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de Contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono de Contacto')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('priority', models.PositiveIntegerField(default=5, help_text='1-10, donde 1 es máxima prioridad', verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor Logístico',
                'verbose_name_plural': 'Proveedores Logísticos',
                'ordering': ['transport_type', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_port', models.CharField(help_text='Ej: SHANGHAI, MIAMI, MADRID', max_length=100, verbose_name='Puerto/Aeropuerto Origen')),
                ('origin_country', models.CharField(max_length=100, verbose_name='País Origen')),
                ('destination', models.CharField(help_text='GYE, PSJ para marítimo. GYE, UIO para aéreo.', max_length=10, verbose_name='Destino Ecuador')),
                ('container_type', models.CharField(blank=True, choices=[('20GP', '1x20GP - General Purpose'), ('40GP', '1x40GP - General Purpose'), ('40HC', '1x40HC - High Cube'), ('40NOR', '1x40NOR - Non-Operating Reefer'), ('20RF', '1x20RF - Reefer 20'), ('40RF', '1x40RF - Reefer 40'), ('20OT', '1x20OT - Open Top'), ('40OT', '1x40OT - Open Top High Cube'), ('20FR', '1x20FR - Flat Rack'), ('40FR', '1x40FR - Flat Rack'), ('45HC', '1x45HC - High Cube 45')], help_text='Solo para FCL', max_length=10, verbose_name='Tipo de Contenedor')),
                ('rate_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa USD')),
                ('unit', models.CharField(choices=[('CONTAINER', 'Por Contenedor'), ('CBM', 'Por Metro Cúbico'), ('TON', 'Por Tonelada'), ('KG', 'Por Kilogramo'), ('WM', 'Por W/M (Mayor CBM o TON)')], default='CONTAINER', max_length=15, verbose_name='Unidad')),
                ('transit_days_min', models.PositiveIntegerField(default=15, verbose_name='Días Tránsito Mínimo')),
                ('transit_days_max', models.PositiveIntegerField(default=25, verbose_name='Días Tránsito Máximo')),
                ('free_days', models.PositiveIntegerField(default=21, help_text='Días libres de almacenaje/demora', verbose_name='Días Libres Demora')),
                ('thc_origin_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='THC Origen USD')),
                ('thc_destination_usd', models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=8, verbose_name='THC Destino USD')),
                ('valid_from', models.DateField(verbose_name='Válido Desde')),
                ('valid_to', models.DateField(verbose_name='Válido Hasta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='SalesModule.logisticsprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Tarifa de Proveedor',
                'verbose_name_plural': 'Tarifas de Proveedores',
                'ordering': ['provider', 'origin_port', 'rate_usd'],
            },
        ),
        migrations.AddIndex(
            model_name='logisticsprovider',
            index=models.Index(fields=['transport_type', 'is_active'], name='SalesModule_transpo_9b0d31_idx'),
        ),
        migrations.AddIndex(
            model_name='providerrate',
            index=models.Index(fields=['provider', 'origin_port', 'destination', 'is_active'], name='SalesModule_provide_c0d421_idx'),
        ),
        migrations.AddIndex(
            model_name='providerrate',
            index=models.Index(fields=['valid_from', 'valid_to'], name='SalesModule_valid_f_8e7455_idx'),
        ),
    ]
