# Generated by Django 4.2.7 on 2025-12-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0020_add_logistics_provider_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Región de Aeropuertos',
                'verbose_name_plural': 'Regiones de Aeropuertos',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(db_index=True, max_length=50, verbose_name='Nombre de Región')),
                ('country', models.CharField(db_index=True, max_length=100, verbose_name='País')),
                ('ciudad_exacta', models.CharField(db_index=True, help_text='Campo principal para búsqueda de usuarios', max_length=150, verbose_name='Ciudad Exacta')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Aeropuerto')),
                ('iata_code', models.CharField(db_index=True, help_text='Código de 3 letras usado internamente para tarifas', max_length=3, unique=True, verbose_name='Código IATA')),
                ('icao_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Código ICAO')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('timezone', models.CharField(blank=True, max_length=50, verbose_name='Zona Horaria')),
                ('is_major_hub', models.BooleanField(default=False, verbose_name='Hub Principal')),
                ('is_cargo_capable', models.BooleanField(default=True, verbose_name='Capacidad de Carga')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='SalesModule.airportregion', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Aeropuerto',
                'verbose_name_plural': 'Aeropuertos',
                'ordering': ['region_name', 'country', 'ciudad_exacta'],
                'indexes': [models.Index(fields=['ciudad_exacta'], name='SalesModule_ciudad__781c9f_idx'), models.Index(fields=['iata_code'], name='SalesModule_iata_co_aaa550_idx'), models.Index(fields=['country', 'ciudad_exacta'], name='SalesModule_country_265e53_idx'), models.Index(fields=['region_name', 'country'], name='SalesModule_region__8ab004_idx'), models.Index(fields=['is_active', 'is_cargo_capable'], name='SalesModule_is_acti_9bb68a_idx')],
            },
        ),
    ]
