# Generated by Django 4.2.7 on 2025-12-12 20:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesModule', '0021_add_airport_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, help_text='MQR-YYYYMMDD-XXXX', max_length=30, null=True, unique=True, verbose_name='Número de Solicitud')),
                ('container_selection', models.JSONField(default=list, help_text='Lista JSON: [{"tipo": "40RF", "cantidad": 2}]', verbose_name='Selección de Contenedores')),
                ('origin', models.CharField(max_length=255, verbose_name='Puerto/Ciudad Origen')),
                ('destination', models.CharField(max_length=255, verbose_name='Puerto/Ciudad Destino')),
                ('cargo_description', models.TextField(verbose_name='Descripción de Carga')),
                ('cargo_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso Total (KG)')),
                ('cargo_volume_cbm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Volumen Total (CBM)')),
                ('special_requirements', models.TextField(blank=True, help_text='Temperatura para REEFER, dimensiones especiales, etc.', verbose_name='Requisitos Especiales')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Temperatura Mínima (°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Temperatura Máxima (°C)')),
                ('company_name', models.CharField(max_length=255, verbose_name='Empresa')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Nombre de Contacto')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('contact_whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada a Agente'), ('en_proceso', 'En Proceso'), ('cotizacion_lista', 'Cotización Lista'), ('enviada', 'Enviada al Cliente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('cost_freight_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo Flete (USD)')),
                ('cost_local_charges_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cargos Locales (USD)')),
                ('cost_special_equipment_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Genset, PTI, etc.', max_digits=12, null=True, verbose_name='Equipo Especial (USD)')),
                ('cost_total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo Total (USD)')),
                ('profit_margin_usd', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=12, verbose_name='Margen de Ganancia (USD)')),
                ('final_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Final (USD)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('transit_time_days', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Tránsito (días)')),
                ('provider_name', models.CharField(blank=True, max_length=255, verbose_name='Naviera/Proveedor')),
                ('internal_notes', models.TextField(blank=True, help_text='Solo visible para administradores', verbose_name='Notas Internas')),
                ('customer_message', models.TextField(blank=True, help_text='Se incluirá en la cotización enviada', verbose_name='Mensaje al Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('quoted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cotización')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_manual_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_quote_requests', to='SalesModule.lead', verbose_name='Lead')),
                ('quote_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_quote_requests', to='SalesModule.quotesubmission', verbose_name='Solicitud de Cotización')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización Manual',
                'verbose_name_plural': 'Solicitudes de Cotización Manual',
                'ordering': ['-created_at'],
            },
        ),
    ]
