# Generated by Django 4.2.7 on 2025-12-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0022_add_manual_quote_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_locode', models.CharField(db_index=True, help_text='Código UN/LOCODE del puerto (ej: USLAX)', max_length=5, unique=True, verbose_name='UN/LOCODE')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre del Puerto')),
                ('country', models.CharField(db_index=True, max_length=100, verbose_name='País')),
                ('region', models.CharField(choices=[('Norteamérica', 'Norteamérica'), ('Latinoamérica', 'Latinoamérica'), ('Europa', 'Europa'), ('África', 'África'), ('Asia', 'Asia'), ('Oceanía', 'Oceanía')], db_index=True, max_length=50, verbose_name='Región')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Puerto',
                'verbose_name_plural': 'Puertos',
                'ordering': ['region', 'country', 'name'],
                'indexes': [models.Index(fields=['un_locode'], name='SalesModule_un_loco_b8ccfa_idx'), models.Index(fields=['name'], name='SalesModule_name_6aaf76_idx'), models.Index(fields=['country'], name='SalesModule_country_980174_idx'), models.Index(fields=['region'], name='SalesModule_region_7dad00_idx')],
            },
        ),
    ]
