# Generated by Django 4.2.7 on 2025-12-12 21:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0023_add_port_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('currency_code', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('GBP', 'Libra Esterlina'), ('CNY', 'Yuan Chino'), ('JPY', 'Yen Japonés')], help_text='Código ISO 4217 de la moneda', max_length=3, primary_key=True, serialize=False, verbose_name='Código de Moneda')),
                ('market_rate', models.DecimalField(decimal_places=6, help_text='Tasa de cambio del mercado (1 USD = X moneda)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tasa de Mercado')),
                ('app_rate', models.DecimalField(decimal_places=6, help_text='Tasa con spread bancario aplicado', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tasa de Aplicación')),
                ('spread_applied', models.DecimalField(decimal_places=4, default=Decimal('0.03'), help_text='Spread bancario aplicado (ej: 0.03 = 3%)', max_digits=5, verbose_name='Spread Aplicado')),
                ('source', models.CharField(default='yfinance', help_text='Fuente de la tasa: yfinance, api, manual', max_length=50, verbose_name='Fuente')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['currency_code'],
            },
        ),
    ]
