# Generated by Django 4.2.7 on 2025-12-12 21:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0024_add_exchange_rate_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='app_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), help_text='Tasa con spread bancario aplicado', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tasa de Aplicación'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='market_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), help_text='Tasa de cambio del mercado (1 USD = X moneda)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tasa de Mercado'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='spread_applied',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.03'), help_text='Spread bancario aplicado (ej: 0.03 = 3%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Spread Aplicado'),
        ),
    ]
