# Generated by Django 4.2.7 on 2025-12-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0025_exchange_rate_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitTimeAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pol', models.CharField(db_index=True, help_text='Código UN/LOCODE del puerto de origen', max_length=10, verbose_name='Puerto Origen (POL)')),
                ('pol_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre Puerto Origen')),
                ('pod', models.CharField(db_index=True, help_text='Código UN/LOCODE del puerto de destino', max_length=10, verbose_name='Puerto Destino (POD)')),
                ('pod_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre Puerto Destino')),
                ('carrier_code', models.CharField(db_index=True, max_length=10, verbose_name='Código Naviera')),
                ('estimated_days', models.CharField(help_text='Rango de días de tránsito (ej: 39-43)', max_length=20, verbose_name='Días Estimados')),
                ('min_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Días Mínimos')),
                ('max_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Días Máximos')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tiempo de Tránsito',
                'verbose_name_plural': 'Tiempos de Tránsito',
                'ordering': ['pol', 'pod', 'carrier_code'],
                'indexes': [models.Index(fields=['pol', 'pod'], name='SalesModule_pol_4b310d_idx'), models.Index(fields=['carrier_code'], name='SalesModule_carrier_a64d7a_idx')],
                'unique_together': {('pol', 'pod', 'carrier_code')},
            },
        ),
        migrations.CreateModel(
            name='CarrierContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_code', models.CharField(db_index=True, help_text='Código de la naviera (MSK, CMA, HPL, ONE, etc.)', max_length=10, verbose_name='Código Naviera')),
                ('carrier_name', models.CharField(help_text='Nombre completo de la línea naviera', max_length=100, verbose_name='Nombre Naviera')),
                ('free_demurrage_days', models.PositiveIntegerField(default=21, help_text='Días libres de demoraje en destino', verbose_name='Días Libres Demora')),
                ('free_detention_days', models.PositiveIntegerField(default=14, help_text='Días libres de detención del contenedor', verbose_name='Días Libres Detención')),
                ('contract_validity', models.DateField(help_text='Fecha hasta la cual la tarifa es válida', verbose_name='Vigencia del Contrato')),
                ('route_type', models.CharField(choices=[('DIRECTA', 'Ruta Directa'), ('TRASBORDO', 'Con Trasbordo'), ('PENDULO', 'Servicio Péndulo')], default='DIRECTA', max_length=20, verbose_name='Tipo de Ruta')),
                ('service_name', models.CharField(blank=True, help_text='Nombre comercial del servicio (ej: AMEX, WCSA)', max_length=100, verbose_name='Nombre del Servicio')),
                ('departure_day', models.CharField(default='Semanal', help_text='Frecuencia de salida (ej: Lunes, Semanal)', max_length=50, verbose_name='Día de Salida')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Contrato de Naviera',
                'verbose_name_plural': 'Contratos de Navieras',
                'ordering': ['carrier_code', '-contract_validity'],
                'unique_together': {('carrier_code', 'contract_validity')},
            },
        ),
    ]
