# Generated by Django 4.2.7 on 2025-12-13 18:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0026_add_carrier_transit_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightRateFCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(default='MARITIMO FCL', editable=False, max_length=20, verbose_name='Tipo de Transporte')),
                ('pol_name', models.CharField(db_index=True, help_text='Nombre del puerto de origen', max_length=100, verbose_name='Puerto de Origen (POL)')),
                ('pod_name', models.CharField(db_index=True, help_text='Nombre del puerto de destino en Ecuador', max_length=100, verbose_name='Puerto de Destino (POD)')),
                ('carrier_name', models.CharField(db_index=True, max_length=150, verbose_name='Naviera')),
                ('validity_date', models.DateField(db_index=True, help_text='Fecha hasta la cual la tarifa es válida', verbose_name='Vigencia Hasta')),
                ('transit_time', models.CharField(blank=True, help_text='Días estimados de tránsito (ej: 35-42)', max_length=20, verbose_name='Tiempo de Tránsito')),
                ('free_days', models.PositiveIntegerField(default=21, help_text='Días libres de demora en destino', verbose_name='Días Libres')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('cost_20gp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo base contenedor 20 pies estándar', max_digits=10, verbose_name='Costo 20GP (USD)')),
                ('cost_40gp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo base contenedor 40 pies estándar', max_digits=10, verbose_name='Costo 40GP (USD)')),
                ('cost_40hc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo base contenedor 40 pies High Cube', max_digits=10, verbose_name='Costo 40HC (USD)')),
                ('cost_nor', models.DecimalField(blank=True, decimal_places=2, help_text='Costo Non Operating Reefer (opcional)', max_digits=10, null=True, verbose_name='Costo 40NOR (USD)')),
                ('includes_thc', models.BooleanField(default=False, help_text='Indica si la tarifa incluye THC en origen', verbose_name='Incluye THC')),
                ('agent_name', models.CharField(blank=True, max_length=150, verbose_name='Agente')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Contrato')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Tarifa FCL',
                'verbose_name_plural': 'Tarifas FCL',
                'ordering': ['pol_name', 'pod_name', 'carrier_name', '-validity_date'],
                'indexes': [models.Index(fields=['pol_name', 'pod_name'], name='SalesModule_pol_nam_94a00d_idx'), models.Index(fields=['carrier_name'], name='SalesModule_carrier_cb6dda_idx'), models.Index(fields=['validity_date', 'is_active'], name='SalesModule_validit_5bb3c5_idx')],
            },
        ),
    ]
