# Generated by Django 4.2.7 on 2025-12-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0027_add_freight_rate_fcl'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightratefcl',
            name='cost_lcl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa LCL por Ton/m3 (Weight/Measure)', max_digits=10, null=True, verbose_name='Costo LCL (USD/W-M)'),
        ),
    ]
