# Generated by Django 4.2.7 on 2025-12-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0028_add_cost_lcl_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightratefcl',
            name='cost_100',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa aérea para +100 kg', max_digits=10, null=True, verbose_name='Tarifa +100KGS'),
        ),
        migrations.AddField(
            model_name='freightratefcl',
            name='cost_1000',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa aérea para +1000 kg', max_digits=10, null=True, verbose_name='Tarifa +1000KGS'),
        ),
        migrations.AddField(
            model_name='freightratefcl',
            name='cost_300',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa aérea para +300 kg', max_digits=10, null=True, verbose_name='Tarifa +300KGS'),
        ),
        migrations.AddField(
            model_name='freightratefcl',
            name='cost_45',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa aérea para +45 kg', max_digits=10, null=True, verbose_name='Tarifa +45KGS'),
        ),
        migrations.AddField(
            model_name='freightratefcl',
            name='cost_500',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa aérea para +500 kg', max_digits=10, null=True, verbose_name='Tarifa +500KGS'),
        ),
        migrations.AddField(
            model_name='freightratefcl',
            name='frequency',
            field=models.CharField(blank=True, help_text='Frecuencia de vuelo (ej: Daily, D135)', max_length=50, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='freightratefcl',
            name='packaging_type',
            field=models.CharField(blank=True, help_text='Tipo de embalaje aceptado (carton, pallet)', max_length=50, verbose_name='Tipo Embalaje'),
        ),
        migrations.AddField(
            model_name='freightratefcl',
            name='routing',
            field=models.CharField(blank=True, help_text='Ruta/Escalas del vuelo', max_length=100, verbose_name='Routing'),
        ),
    ]
