# Generated by Django 4.2.7 on 2025-12-13 19:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0029_add_air_freight_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDestinationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del gasto', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código interno (ej: DTHC, HANDLING)', max_length=30, verbose_name='Código')),
                ('transport_type', models.CharField(choices=[('MARITIMO_FCL', 'Marítimo FCL'), ('MARITIMO_LCL', 'Marítimo LCL'), ('AEREO', 'Aéreo'), ('ALL', 'Todos')], db_index=True, max_length=20, verbose_name='Tipo de Transporte')),
                ('cost_type', models.CharField(choices=[('THC_DESTINO', 'THC Destino'), ('HANDLING', 'Handling'), ('DOC_FEE', 'Document Fee'), ('BL_FEE', 'BL Fee'), ('DESCONSOLIDACION', 'Desconsolidación'), ('ALMACENAJE_BASE', 'Almacenaje Base'), ('MOVILIZACION', 'Movilización'), ('INSPECCION', 'Inspección'), ('AFORO', 'Aforo'), ('TRANSMISION', 'Transmisión DAE'), ('OTROS', 'Otros')], db_index=True, max_length=30, verbose_name='Tipo de Costo')),
                ('port', models.CharField(choices=[('GYE', 'Guayaquil'), ('PSJ', 'Puerto Bolívar'), ('MEC', 'Manta'), ('ESM', 'Esmeraldas'), ('UIO', 'Quito (Aéreo)'), ('ALL', 'Todos los Puertos')], default='ALL', max_length=10, verbose_name='Puerto/Aeropuerto')),
                ('container_type', models.CharField(choices=[('20GP', '20GP'), ('40GP', '40GP'), ('40HC', '40HC'), ('40NOR', '40NOR'), ('LCL', 'LCL (por CBM/TON)'), ('KG', 'Por Kilogramo'), ('ALL', 'Todos')], default='ALL', max_length=10, verbose_name='Tipo Contenedor')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo USD')),
                ('cost_per_unit', models.CharField(default='CONTENEDOR', help_text='CONTENEDOR, CBM, TON, KG, BL, etc.', max_length=30, verbose_name='Por Unidad')),
                ('is_iva_exempt', models.BooleanField(default=False, help_text='DTHC en FCL marítimo está exento de IVA', verbose_name='Exento de IVA')),
                ('exemption_reason', models.CharField(blank=True, max_length=200, verbose_name='Razón Exención')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Si es obligatorio incluir en toda cotización', verbose_name='Obligatorio')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('validity_start', models.DateField(blank=True, null=True, verbose_name='Vigencia Desde')),
                ('validity_end', models.DateField(blank=True, null=True, verbose_name='Vigencia Hasta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Gasto Local en Destino',
                'verbose_name_plural': 'Gastos Locales en Destino',
                'ordering': ['transport_type', 'cost_type', 'port'],
            },
        ),
        migrations.CreateModel(
            name='ProfitMarginConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la configuración', max_length=100, verbose_name='Nombre')),
                ('transport_type', models.CharField(choices=[('MARITIMO_FCL', 'Marítimo FCL'), ('MARITIMO_LCL', 'Marítimo LCL'), ('AEREO', 'Aéreo'), ('TERRESTRE', 'Terrestre'), ('ALL', 'Todos')], db_index=True, max_length=20, verbose_name='Tipo de Transporte')),
                ('item_type', models.CharField(choices=[('FLETE', 'Flete Internacional'), ('THC_ORIGEN', 'THC Origen'), ('THC_DESTINO', 'THC Destino'), ('HANDLING', 'Handling'), ('DOC_FEE', 'Document Fee'), ('BL_FEE', 'BL Fee'), ('SEGURO', 'Seguro'), ('ALMACENAJE', 'Almacenaje'), ('TRANSPORTE_LOCAL', 'Transporte Local'), ('AGENCIAMIENTO', 'Agenciamiento Aduanero'), ('OTROS', 'Otros Gastos'), ('ALL', 'Todos los Rubros')], db_index=True, max_length=30, verbose_name='Tipo de Rubro')),
                ('margin_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED', 'Monto Fijo'), ('MINIMUM', 'Mínimo Garantizado')], default='PERCENTAGE', max_length=20, verbose_name='Tipo de Margen')),
                ('margin_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 15.00) o monto fijo en USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor del Margen')),
                ('minimum_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Margen mínimo garantizado en USD (aplica cuando margin_type=PERCENTAGE)', max_digits=10, null=True, verbose_name='Margen Mínimo USD')),
                ('priority', models.IntegerField(default=10, help_text='Menor número = mayor prioridad. Usa esto para sobrescribir reglas generales.', verbose_name='Prioridad')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de Margen',
                'verbose_name_plural': 'Configuraciones de Márgenes',
                'ordering': ['priority', 'transport_type', 'item_type'],
                'unique_together': {('transport_type', 'item_type', 'margin_type')},
            },
        ),
    ]
