# Generated by Django 4.2.7 on 2025-12-13 20:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0030_profit_margin_and_local_costs'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, help_text='Valor mínimo del rango de mercancía', max_digits=14, verbose_name='Valor Mínimo (USD)')),
                ('max_value', models.DecimalField(decimal_places=2, help_text='Valor máximo del rango de mercancía', max_digits=14, verbose_name='Valor Máximo (USD)')),
                ('fixed_fee', models.DecimalField(decimal_places=2, help_text='Prima de seguro fija para este rango', max_digits=12, verbose_name='Prima Fija (USD)')),
                ('rate_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.35'), help_text='Tasa porcentual de referencia (0.35% por defecto)', max_digits=6, verbose_name='Tasa (%)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('description', models.TextField(blank=True, help_text='Texto original de la regla de seguro', verbose_name='Descripción')),
                ('iva_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje de IVA local aplicable', max_digits=5, verbose_name='IVA (%)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tramo de Seguro',
                'verbose_name_plural': 'Tramos de Seguro',
                'ordering': ['min_value'],
                'indexes': [models.Index(fields=['min_value', 'max_value', 'is_active'], name='SalesModule_min_val_4ef9ca_idx')],
            },
        ),
    ]
