# Generated by Django 4.2.7 on 2025-12-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0031_insurance_bracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='fob_value_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor FOB aproximado de la mercancía', max_digits=12, null=True, verbose_name='Valor FOB (USD)'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='hs_code_known',
            field=models.CharField(blank=True, help_text='Partida arancelaria si el cliente la conoce', max_length=20, verbose_name='Código HS (Conocido)'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='product_description',
            field=models.TextField(blank=True, help_text='Descripción específica del producto para clasificación HS', verbose_name='Descripción Detallada del Producto'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='product_origin_country',
            field=models.CharField(blank=True, help_text='País de fabricación/origen del producto', max_length=100, verbose_name='País de Origen del Producto'),
        ),
        migrations.CreateModel(
            name='QuoteSubmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('factura_comercial', 'Factura Comercial'), ('packing_list', 'Packing List'), ('permiso_arcsa', 'Permiso ARCSA'), ('permiso_agrocalidad', 'Permiso AGROCALIDAD'), ('certificado_inen', 'Certificado INEN'), ('msds', 'MSDS - Hoja de Seguridad'), ('ficha_tecnica', 'Ficha Técnica'), ('otro', 'Otro Documento')], default='otro', max_length=30, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='quote_documents/%Y/%m/', verbose_name='Archivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file_size', models.IntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('quote_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='SalesModule.quotesubmission', verbose_name='Solicitud de Cotización')),
            ],
            options={
                'verbose_name': 'Documento de Cotización',
                'verbose_name_plural': 'Documentos de Cotización',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
