# Generated by Django 4.2.7 on 2025-12-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0032_add_product_fields_and_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='company_ruc',
            field=models.CharField(blank=True, help_text='13 dígitos numéricos del RUC Ecuador', max_length=13, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='customs_alert_sent',
            field=models.BooleanField(default=False, verbose_name='Alerta Aduanas Enviada'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='is_first_quote',
            field=models.BooleanField(default=True, help_text='Indica si es la primera cotización del cliente', verbose_name='¿Es Primera Cotización?'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='is_oce_registered',
            field=models.BooleanField(default=False, help_text='Operador de Comercio Exterior registrado ante SENAE', verbose_name='¿Es OCE Registrado?'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='vendor_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación Forwarder'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='vendor_validation_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('existing_client', 'Cliente Existente'), ('new_client', 'Cliente Nuevo'), ('not_required', 'No Requerido')], default='not_required', help_text='Estado de validación del cliente con el forwarder', max_length=30, verbose_name='Estado Validación Forwarder'),
        ),
    ]
