# Generated by Django 4.2.7 on 2025-12-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0033_add_ruc_oce_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='containers_detail',
            field=models.TextField(blank=True, help_text='JSON con detalles de cada contenedor para FCL', verbose_name='Detalle de Contenedores'),
        ),
        migrations.AlterField(
            model_name='quotesubmission',
            name='container_type',
            field=models.CharField(blank=True, help_text='Resumen de contenedores para FCL, ej: 2x40HC + 1x20GP', max_length=100, verbose_name='Tipo de Contenedor'),
        ),
    ]
