# Generated by Django 4.2.7 on 2025-12-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0034_quotesubmission_containers_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='destination_ports',
            field=models.TextField(blank=True, help_text='JSON array de puertos de destino', verbose_name='Puertos de Destino (JSON)'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='is_multi_port_quote',
            field=models.BooleanField(default=False, help_text='Si hay múltiples POL o POD', verbose_name='Es Cotización Multi-Puerto'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='origin_ports',
            field=models.TextField(blank=True, help_text='JSON array de puertos de origen', verbose_name='Puertos de Origen (JSON)'),
        ),
    ]
