# Generated by Django 4.2.7 on 2025-12-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0035_quotesubmission_destination_ports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_address',
            field=models.TextField(blank=True, help_text='Dirección completa ingresada por el lead', verbose_name='Dirección Entrega Terrestre'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_address_validated',
            field=models.TextField(blank=True, help_text='Dirección exacta validada por Gemini AI', verbose_name='Dirección Validada por IA'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_address_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dirección Validada En'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_ai_response',
            field=models.TextField(blank=True, help_text='JSON de respuesta de Gemini para validación de dirección', verbose_name='Respuesta IA Dirección'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad Destino Terrestre'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_forwarder_email_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Email Forwarder'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_forwarder_notified',
            field=models.BooleanField(default=False, verbose_name='Forwarder Notificado'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_forwarder_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Forwarder Notificado En'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_google_maps_link',
            field=models.URLField(blank=True, help_text='Link de Google Maps generado por IA', max_length=500, verbose_name='Link Google Maps'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='inland_transport_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='needs_inland_transport',
            field=models.BooleanField(default=False, verbose_name='Requiere Transporte Terrestre'),
        ),
    ]
