# Generated by Django 4.2.7 on 2025-12-14 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesModule', '0036_add_inland_transport_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_number', models.CharField(blank=True, help_text='RO-IMP-2025-00001', max_length=30, null=True, unique=True, verbose_name='Número de RO')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('documents_pending', 'Documentos Pendientes'), ('documents_uploaded', 'Documentos Subidos'), ('ai_processing', 'Procesando AI'), ('ai_processed', 'AI Procesado'), ('pending_review', 'Pendiente Revisión'), ('finalized', 'Finalizado'), ('ro_generated', 'RO Generado'), ('sent_to_forwarder', 'Enviado a Forwarder'), ('forwarder_confirmed', 'Forwarder Confirmado')], default='draft', max_length=30, verbose_name='Estado')),
                ('shipper_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Shipper')),
                ('shipper_address', models.TextField(blank=True, verbose_name='Dirección del Shipper')),
                ('shipper_tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID / RUC Shipper')),
                ('shipper_contact', models.CharField(blank=True, max_length=255, verbose_name='Contacto Shipper')),
                ('shipper_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Shipper')),
                ('shipper_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Shipper')),
                ('consignee_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Consignatario')),
                ('consignee_address', models.TextField(blank=True, verbose_name='Dirección del Consignatario')),
                ('consignee_tax_id', models.CharField(blank=True, max_length=13, verbose_name='RUC Consignatario')),
                ('consignee_contact', models.CharField(blank=True, max_length=255, verbose_name='Contacto Consignatario')),
                ('consignee_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Consignatario')),
                ('consignee_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Consignatario')),
                ('notify_party_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Notify Party')),
                ('notify_party_address', models.TextField(blank=True, verbose_name='Dirección Notify Party')),
                ('notify_party_contact', models.CharField(blank=True, max_length=255, verbose_name='Contacto Notify Party')),
                ('notify_party_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Notify Party')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Descripción de Carga')),
                ('hs_codes', models.CharField(blank=True, help_text='Códigos separados por coma', max_length=255, verbose_name='Códigos HS')),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso Bruto (KG)')),
                ('net_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso Neto (KG)')),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Volumen (CBM)')),
                ('packages_count', models.IntegerField(blank=True, null=True, verbose_name='Número de Bultos')),
                ('packages_type', models.CharField(blank=True, help_text='CAJAS, PALLETS, BULTOS, etc.', max_length=50, verbose_name='Tipo de Embalaje')),
                ('packages_marks', models.TextField(blank=True, verbose_name='Marcas y Números')),
                ('container_numbers', models.TextField(blank=True, help_text='Números separados por coma o JSON', verbose_name='Números de Contenedor')),
                ('seal_numbers', models.TextField(blank=True, help_text='Sellos separados por coma o JSON', verbose_name='Números de Sello')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Factura')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Factura')),
                ('invoice_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Factura (USD)')),
                ('packing_list_ref', models.CharField(blank=True, max_length=100, verbose_name='Referencia Packing List')),
                ('ai_extracted_data', models.JSONField(blank=True, default=dict, help_text='JSON con datos extraídos automáticamente de documentos', verbose_name='Datos Extraídos por AI')),
                ('ai_confidence_map', models.JSONField(blank=True, default=dict, help_text='JSON con nivel de confianza por campo (0-100)', verbose_name='Mapa de Confianza AI')),
                ('is_ai_processed', models.BooleanField(default=False, verbose_name='Procesado por AI')),
                ('ai_processing_errors', models.TextField(blank=True, verbose_name='Errores de Procesamiento AI')),
                ('external_forwarder_ref', models.CharField(blank=True, help_text='Número de referencia/RO del freight forwarder', max_length=100, verbose_name='Referencia Externa Forwarder')),
                ('forwarder_email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email a Forwarder Enviado')),
                ('forwarder_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Forwarder Confirmó')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instrucciones Especiales')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_instructions', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('quote_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_instruction', to='SalesModule.quotesubmission', verbose_name='Solicitud de Cotización')),
            ],
            options={
                'verbose_name': 'Instrucción de Embarque',
                'verbose_name_plural': 'Instrucciones de Embarque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingInstructionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Factura Comercial'), ('packing_list', 'Packing List'), ('origin_cert', 'Certificado de Origen'), ('inen_cert', 'Certificado INEN'), ('arcsa_cert', 'Registro Sanitario ARCSA'), ('agrocalidad_cert', 'Certificado AGROCALIDAD'), ('phyto_cert', 'Certificado Fitosanitario'), ('zoo_cert', 'Certificado Zoosanitario'), ('insurance_cert', 'Certificado de Seguro'), ('bl_draft', 'BL Draft'), ('awb_draft', 'AWB Draft'), ('booking_confirmation', 'Confirmación de Booking'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='shipping_instructions/documents/%Y/%m/', verbose_name='Archivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file_size', models.IntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('extracted_text', models.TextField(blank=True, help_text='Texto OCR extraído del documento', verbose_name='Texto Extraído')),
                ('extracted_json', models.JSONField(blank=True, default=dict, help_text='Datos estructurados extraídos por AI', verbose_name='Datos Extraídos (JSON)')),
                ('gemini_job_id', models.CharField(blank=True, help_text='ID del job de procesamiento en Gemini', max_length=100, verbose_name='Gemini Job ID')),
                ('processing_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('manual_review', 'Revisión Manual')], default='pending', max_length=20, verbose_name='Estado de Procesamiento')),
                ('processing_error', models.TextField(blank=True, verbose_name='Error de Procesamiento')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesamiento Iniciado')),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesamiento Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('shipping_instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='SalesModule.shippinginstruction', verbose_name='Instrucción de Embarque')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_si_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento de SI',
                'verbose_name_plural': 'Documentos de SI',
                'ordering': ['-created_at'],
            },
        ),
    ]
