# Generated by Django 4.2.7 on 2025-12-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0037_shipping_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_key', models.CharField(choices=[('SI_ENVIADA', '1. SI Enviada'), ('SI_RECIBIDA_FORWARDER', '2. SI Recibida por Forwarder'), ('SHIPPER_CONTACTADO', '3. Shipper Contactado'), ('BOOKING_ORDER_RECIBIDA', '4. Booking Order Recibida en Origen'), ('ETD_SOLICITADO', '5. ETD Solicitado / Gestionando Reserva'), ('BOOKING_CONFIRMADO', '6. Booking Confirmado'), ('SO_LIBERADO', '7. S/O Liberado al Shipper'), ('RETIRO_CARGUE_VACIOS', '8. Fecha Retiro y Cargue de Vacíos'), ('CONTENEDORES_CARGADOS', '9. Contenedores Cargados'), ('GATE_IN', '10. Gate In (Entrada Terminal Origen)'), ('ETD', '11. ETD (Estimated Time of Departure)'), ('ATD', '12. ATD (Actual Time of Departure)'), ('TRANSHIPMENT', '13. Transhipment Date'), ('ETA_DESTINO', '14. ETA Destino Final')], max_length=30, verbose_name='Clave del Hito')),
                ('milestone_order', models.IntegerField(default=0, help_text='Orden secuencial del hito (1-14)', verbose_name='Orden del Hito')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('planned_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Planificada')),
                ('actual_date', models.DateTimeField(blank=True, help_text='Cuando se completa, dispara el cambio visual a completado', null=True, verbose_name='Fecha Real')),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales como Cut-offs para Booking Confirmado', verbose_name='Metadatos')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('shipping_instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='SalesModule.shippinginstruction', verbose_name='Instrucción de Embarque')),
            ],
            options={
                'verbose_name': 'Hito de Embarque',
                'verbose_name_plural': 'Hitos de Embarque',
                'ordering': ['shipping_instruction', 'milestone_order'],
                'unique_together': {('shipping_instruction', 'milestone_key')},
            },
        ),
    ]
