# Generated by Django 4.2.7 on 2025-12-14 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesModule', '0038_add_shipment_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliquidation',
            name='assistance_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Asistencia'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='assistance_requested',
            field=models.BooleanField(default=False, verbose_name='Asistencia Solicitada'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='assistance_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Solicitud Asistencia'),
        ),
        migrations.AddField(
            model_name='preliquidation',
            name='assistance_status',
            field=models.CharField(choices=[('none', 'Sin Solicitud'), ('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completada')], default='none', max_length=20, verbose_name='Estado Asistencia'),
        ),
        migrations.CreateModel(
            name='PreLiquidationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('factura_comercial', 'Factura Comercial'), ('packing_list', 'Packing List'), ('certificado_origen', 'Certificado de Origen'), ('ficha_tecnica', 'Ficha Técnica'), ('permiso_previo', 'Permiso Previo'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de Documento')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('pre_liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='SalesModule.preliquidation', verbose_name='Pre-Liquidación')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_preliq_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
            ],
            options={
                'verbose_name': 'Documento Pre-Liquidación',
                'verbose_name_plural': 'Documentos Pre-Liquidación',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
