# Generated by Django 4.2.7 on 2025-12-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0039_preliq_assistance_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliquidation',
            name='quote_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_liquidations', to='SalesModule.quotesubmission', verbose_name='Solicitud de Cotización'),
        ),
        migrations.AlterField(
            model_name='preliquidation',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_liquidations', to='SalesModule.leadcotizacion', verbose_name='Cotización'),
        ),
    ]
