# Generated by Django 4.2.7 on 2025-12-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0040_add_quote_submission_to_preliquidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='localdestinationcost',
            name='carrier_code',
            field=models.CharField(blank=True, db_index=True, help_text='Código de naviera (ONE, MSK, CMA, etc.) - Solo para FCL. Dejar vacío para LCL/AEREO.', max_length=20, null=True, verbose_name='Código Naviera'),
        ),
    ]
