# Generated by Django 4.2.7 on 2025-12-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0041_add_carrier_code_to_local_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='cargo_pieces_detail',
            field=models.TextField(blank=True, help_text='JSON con detalles de cada pieza/bulto para LCL/Aéreo: dimensiones, cantidad, embalaje', verbose_name='Detalle de Piezas de Carga'),
        ),
    ]
