# Generated by Django 4.2.7 on 2025-12-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0042_add_cargo_pieces_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preliquidation',
            name='confirmed_hs_code',
            field=models.CharField(blank=True, max_length=25, verbose_name='Código HS Confirmado'),
        ),
        migrations.AlterField(
            model_name='preliquidation',
            name='suggested_hs_code',
            field=models.CharField(blank=True, max_length=25, verbose_name='Código HS Sugerido'),
        ),
    ]
