# Generated by Django 4.2.7 on 2025-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0043_increase_hs_code_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesubmission',
            name='status',
            field=models.CharField(choices=[('recibida', 'Recibida'), ('validacion_pendiente', 'Validación Pendiente'), ('procesando_costos', 'Procesando Costos'), ('en_espera_ff', 'En Espera Freight Forwarder'), ('cotizacion_generada', 'Cotización Generada'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('ro_generado', 'RO Generado'), ('en_transito', 'En Tránsito'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('error_validacion', 'Error en Validación'), ('error_costos', 'Error en Costos')], default='recibida', max_length=30, verbose_name='Estado'),
        ),
    ]
