# Generated by Django 4.2.7 on 2025-12-21 20:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesModule', '0044_add_en_espera_ff_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightForwarderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Freight Forwarder')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Nombre de Contacto')),
                ('contact_email', models.EmailField(help_text='Email donde se enviarán las solicitudes de cotización', max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono de Contacto')),
                ('cc_admin_email', models.EmailField(blank=True, help_text='Email del Master Admin para copia de notificaciones', max_length=254, verbose_name='Email Admin (CC)')),
                ('default_profit_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Margen de Ganancia por Defecto (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración de Freight Forwarder',
                'verbose_name_plural': 'Configuraciones de Freight Forwarders',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FFQuoteCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('uploaded', 'Costos Subidos'), ('processed', 'Procesado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('origin_costs_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Incluye pickup, handling, documentación en origen', max_digits=12, verbose_name='Gastos de Origen (USD)')),
                ('origin_costs_detail', models.JSONField(blank=True, default=dict, help_text='JSON con desglose de gastos de origen', verbose_name='Detalle Gastos Origen')),
                ('freight_cost_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Flete Internacional (USD)')),
                ('carrier_name', models.CharField(blank=True, max_length=150, verbose_name='Naviera/Aerolínea')),
                ('transit_time', models.CharField(blank=True, help_text='Días estimados, ej: 35-42', max_length=50, verbose_name='Tiempo de Tránsito')),
                ('destination_costs_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='THC, handling, documentación en destino', max_digits=12, verbose_name='Gastos en Destino (USD)')),
                ('destination_costs_detail', models.JSONField(blank=True, default=dict, verbose_name='Detalle Gastos Destino')),
                ('profit_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Margen de Ganancia (%)')),
                ('total_ff_cost_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Suma de origen + flete + destino', max_digits=12, verbose_name='Total Costo FF (USD)')),
                ('total_with_margin_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total incluyendo margen de ganancia', max_digits=12, verbose_name='Total con Margen (USD)')),
                ('ff_reference', models.CharField(blank=True, help_text='Número de referencia del freight forwarder', max_length=100, verbose_name='Referencia FF')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Vigencia Hasta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('ff_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Notificación a FF')),
                ('ff_response_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Respuesta FF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('ff_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_costs', to='SalesModule.freightforwarderconfig', verbose_name='Freight Forwarder')),
                ('quote_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ff_quote_cost', to='SalesModule.quotesubmission', verbose_name='Solicitud de Cotización')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ff_cost_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Costo de Cotización FF',
                'verbose_name_plural': 'Costos de Cotizaciones FF',
                'ordering': ['-created_at'],
            },
        ),
    ]
