# Generated by Django 4.2.7 on 2025-12-21 21:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0045_add_ff_config_and_costs'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlandSecurityTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(db_index=True, default='GYE', max_length=100, verbose_name='Ciudad Origen')),
                ('destination_city', models.CharField(db_index=True, max_length=100, verbose_name='Ciudad Destino')),
                ('route_name', models.CharField(help_text='Ej: GYE-UIO-GYE', max_length=100, verbose_name='Nombre de Ruta')),
                ('service_type', models.CharField(choices=[('CUSTODIA_ARMADA', 'Custodia Armada'), ('CANDADO_SATELITAL', 'Candado Satelital')], max_length=30, verbose_name='Tipo de Servicio')),
                ('base_rate_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa Base (USD)')),
                ('iva_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Tasa IVA (%)')),
                ('iva_applies', models.BooleanField(default=True, verbose_name='Aplica IVA')),
                ('valid_from', models.DateField(auto_now_add=True, verbose_name='Válido Desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tarifa Seguridad Transporte',
                'verbose_name_plural': 'Tarifas Seguridad Transporte',
                'ordering': ['service_type', 'destination_city'],
                'indexes': [models.Index(fields=['destination_city', 'service_type', 'is_active'], name='SalesModule_destina_91f2bd_idx')],
                'unique_together': {('origin_city', 'destination_city', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='InlandFCLTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(db_index=True, default='GYE', max_length=100, verbose_name='Ciudad Origen')),
                ('destination_city', models.CharField(db_index=True, max_length=100, verbose_name='Ciudad Destino')),
                ('route_name', models.CharField(help_text='Ej: GYE-UIO-GYE', max_length=100, verbose_name='Nombre de Ruta')),
                ('container_type', models.CharField(choices=[('20GP', '20GP'), ('40GP', '40GP'), ('40HC', '40HC'), ('40NOR', '40NOR'), ('20REEFER', '20 Reefer'), ('40REEFER', '40 Reefer'), ('ALL', 'Todos los contenedores')], default='ALL', max_length=20, verbose_name='Tipo Contenedor')),
                ('rate_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa Base (USD)')),
                ('is_round_trip', models.BooleanField(default=True, help_text='Incluye retorno', verbose_name='Viaje Redondo')),
                ('empty_return_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('56.00'), max_digits=8, verbose_name='Turno Devolución Vacío (USD)')),
                ('empty_return_iva_applies', models.BooleanField(default=True, verbose_name='Turno Devolución con IVA')),
                ('free_loading_hours', models.IntegerField(default=6, verbose_name='Horas Libres Carga/Descarga')),
                ('hour_7_to_10_rate_usd', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=8, verbose_name='Tarifa Hora 7-10 (USD)')),
                ('hour_11_plus_percent', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5, verbose_name='% Flete Hora 11+')),
                ('false_freight_percent', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5, verbose_name='% Falso Flete')),
                ('valid_from', models.DateField(auto_now_add=True, verbose_name='Válido Desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tarifa Transporte Terrestre FCL',
                'verbose_name_plural': 'Tarifas Transporte Terrestre FCL',
                'ordering': ['destination_city'],
                'indexes': [models.Index(fields=['destination_city', 'is_active'], name='SalesModule_destina_318b60_idx'), models.Index(fields=['origin_city', 'destination_city', 'is_active'], name='SalesModule_origin__fd3129_idx')],
                'unique_together': {('origin_city', 'destination_city', 'container_type')},
            },
        ),
    ]
