# Generated by Django 4.2.7 on 2025-12-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0046_inland_fcl_security_tariffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='wants_armed_custody',
            field=models.BooleanField(default=False, help_text='Servicio de escolta armada para transporte terrestre FCL', verbose_name='Requiere Custodia Armada'),
        ),
        migrations.AddField(
            model_name='quotesubmission',
            name='wants_satellite_lock',
            field=models.BooleanField(default=False, help_text='Servicio de rastreo GPS satelital para contenedor', verbose_name='Requiere Candado Satelital'),
        ),
    ]
