# Generated by Django 4.2.7 on 2025-12-23 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesModule', '0047_add_security_services_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginstruction',
            name='assigned_ff_user',
            field=models.ForeignKey(blank=True, help_text='Usuario FF responsable de actualizar tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Freight Forwarder Asignado'),
        ),
        migrations.AddField(
            model_name='shippinginstruction',
            name='ff_assignment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación FF'),
        ),
    ]
