# Generated by Django 4.2.7 on 2025-12-23 06:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0048_ff_portal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCodeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(help_text='Subpartida arancelaria (ej: 8471.30.00)', max_length=15, unique=True, verbose_name='Código HS')),
                ('description', models.TextField(help_text='Descripción del producto según el arancel', verbose_name='Descripción')),
                ('description_en', models.TextField(blank=True, help_text='Descripción en inglés para búsquedas', verbose_name='Descripción (Inglés)')),
                ('category', models.CharField(blank=True, help_text='Categoría general (Electrónicos, Textiles, etc.)', max_length=100, verbose_name='Categoría')),
                ('chapter', models.CharField(blank=True, help_text='Capítulo del arancel (01-99)', max_length=10, verbose_name='Capítulo')),
                ('ad_valorem_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de Ad-Valorem (0-45)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tasa Ad-Valorem')),
                ('ice_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ICE (solo productos especiales)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tasa ICE')),
                ('unit', models.CharField(default='kg', help_text='Unidad para cálculo (kg, unidad, litro, etc.)', max_length=20, verbose_name='Unidad de Medida')),
                ('requires_permit', models.BooleanField(default=False, verbose_name='Requiere Permiso Previo')),
                ('permit_institution', models.CharField(blank=True, choices=[('', 'Ninguno'), ('ARCSA', 'ARCSA - Alimentos, cosméticos, medicamentos'), ('AGROCALIDAD', 'AGROCALIDAD - Productos agropecuarios'), ('INEN', 'INEN - Certificados de conformidad'), ('CONSEP', 'CONSEP/Min. Interior - Sustancias controladas'), ('MAG', 'MAG/MAATE - Productos forestales'), ('DEFENSA', 'Min. Defensa - Armas y municiones')], default='', max_length=20, verbose_name='Institución de Permiso')),
                ('permit_name', models.CharField(blank=True, help_text='Nombre del permiso requerido', max_length=200, verbose_name='Nombre del Permiso')),
                ('permit_processing_days', models.CharField(blank=True, help_text='Tiempo estimado del trámite (ej: 15-30 días)', max_length=50, verbose_name='Tiempo de Trámite')),
                ('keywords', models.TextField(blank=True, help_text='Palabras clave separadas por comas para búsqueda IA', verbose_name='Palabras Clave')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el producto', verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Partida Arancelaria',
                'verbose_name_plural': 'Partidas Arancelarias',
                'ordering': ['hs_code'],
                'indexes': [models.Index(fields=['hs_code'], name='SalesModule_hs_code_94b991_idx'), models.Index(fields=['category'], name='SalesModule_categor_9a2564_idx'), models.Index(fields=['is_active'], name='SalesModule_is_acti_6aa0ef_idx')],
            },
        ),
    ]
