# Generated by Django 4.2.7 on 2025-12-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesModule', '0049_hs_code_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('FCL', 'FCL - Full Container Load'), ('LCL', 'LCL - Less than Container Load'), ('AIR', 'AIR - Carga Aérea')], max_length=10, verbose_name='Tipo de Transporte')),
                ('milestone_name', models.CharField(max_length=100, verbose_name='Nombre del Hito')),
                ('milestone_order', models.IntegerField(default=1, help_text='Orden secuencial del hito dentro del tipo de transporte', verbose_name='Orden del Hito')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del hito', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Tracking',
                'verbose_name_plural': 'Plantillas de Tracking',
                'ordering': ['transport_type', 'milestone_order'],
                'unique_together': {('transport_type', 'milestone_order')},
            },
        ),
    ]
