# Generated by Django 4.2.7 on 2025-12-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('quote_created', 'Cotización Creada'), ('quote_approved', 'Cotización Aprobada'), ('quote_rejected', 'Cotización Rechazada'), ('ro_generated', 'RO Generado'), ('shipment_created', 'Embarque Creado'), ('shipment_updated', 'Embarque Actualizado'), ('user_created', 'Usuario Creado'), ('user_updated', 'Usuario Actualizado'), ('ruc_approved', 'RUC Aprobado'), ('ruc_rejected', 'RUC Rechazado'), ('document_uploaded', 'Documento Subido'), ('preliq_created', 'Pre-Liquidación Creada'), ('system_error', 'Error del Sistema'), ('api_call', 'Llamada API'), ('config_changed', 'Configuración Modificada'), ('other', 'Otro')], db_index=True, default='other', max_length=50)),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SUCCESS', 'Éxito')], db_index=True, default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_email', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=100)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'masteradmin_activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='masteradmin_action__fbcd5a_idx'), models.Index(fields=['user_id', 'created_at'], name='masteradmin_user_id_1fca67_idx')],
            },
        ),
    ]
